### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by paldier** [aa65535/openwrt-chinadns#10]
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)/$(PKG_NAME)-$(PKG_VERSION)
是不是应该修改为
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)/openwrt-chinadns-$(PKG_VERSION)
？
不过修改了我这里依然编译失败

**Comment by aa65535** [comment]
使用 `V=s` 编译，并将报错信息 post 上来

**Comment by aa65535** [comment]
`PKG_BUILD_DIR` 的路径没错，不要去修改。
