### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by suikatomoki** [aa65535/openwrt-chinadns#100]

**Comment by suikatomoki** [comment]
我觉得 chinadns 比 overture 更适合部署在路由器上

**Comment by Biercenter** [comment]
我暂时用DNS Forwarder解决，如果chinadns自带最好，哈哈

**Comment by suikatomoki** [comment]
@Biercenter 如何解决移动长城联动劫持 114 119 之类的国内公共 DNS 到他们自己的DNS服务器上 分享一下你的解决方案

**Comment by Biercenter** [comment]
@suikatomoki 这个我这边没出现过，看看114之类的有没有支持tcp查询的，或者换腾讯，阿里，中科大的DNS试试。 我这边国内填114正常，国外通过dns forwarder换成tcp到谷歌的8.8.8.8查询。你也可以使用命令行看看，是不是真的给劫持到长城的服务器。

**Comment by Biercenter** [comment]
@suikatomoki 实在不行也可以把常用的域名直接写到dnsmasq或者hosts，其它全部使用国外的查询。

**Comment by suikatomoki** [comment]
@Biercenter 我只是想隐晦的表达 DNS Forwarder 解决不了国内公共 DNS 劫持
@aa65535 119.29.29.29 解析某些国外域名被劫持到移动自己的 DNS 服务器上去了 返回一个省内 IP 段 导致 ChinaDNS 工作异常 我一脸懵逼 跟这个类似 https://github.com/aa65535/openwrt-chinadns/issues/65

**Comment by zong400** [comment]
我这里广东的使用chinadns+dns-forwarder已经不行了
改用DNSCrypt才能正确解析
