### ISSUE TITLE
[wiki doc] what is `option local '127.0.0.1#5353'`? why not `list server '127.0.0.1#5353'`?

### ISSUE THREAD

**Issue by sgon00** [aa65535/openwrt-chinadns#101]
Hi, in the wiki page https://github.com/aa65535/openwrt-chinadns/wiki/Use-DNS-Forwarder, it has the following config:

```
config dnsmasq
	option local '127.0.0.1#5353'
```

I have no idea why it uses `option local`. In the openwrt official doc https://openwrt.org/docs/guide-user/base-system/dhcp, the `local` defines `Look up DNS entries for this domain from /etc/hosts.`.

I think it should be `list server '127.0.0.1#5353'` which always works for me. 

Thanks.

**Comment by aa65535** [comment]
They are equivalent.
