### ISSUE TITLE
无法解析某些域名

### ISSUE THREAD

**Issue by isbaseby** [aa65535/openwrt-chinadns#11]
chinadns版本是最新版，上游服务器为114.114.114.114,8.8.4.4 

举例
root@OpenWrt:~# dig ss06.8ke.co

; <<>> DiG 9.9.4 <<>> ss06.8ke.co
;; global options: +cmd
;; connection timed out; no servers could be reached
root@OpenWrt:~# dig ss06.8ke.co @8.8.8.8

; <<>> DiG 9.9.4 <<>> ss06.8ke.co @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52542
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ss06.8ke.co.                   IN      A

;; ANSWER SECTION:
ss06.8ke.co.            35      IN      A       103.226.125.101
ss06.8ke.co.            35      IN      A       207.226.143.34
ss06.8ke.co.            35      IN      A       118.193.150.214

;; Query time: 120 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Feb 11 22:35:21 CST 2015
;; MSG SIZE  rcvd: 88

**Comment by aa65535** [comment]
无法重现，请检查你的设置。
另外，第一次 dig 时指定的服务器是否是 chinadns 都不得而知。

**Comment by isbaseby** [comment]
请问应该检查什么地方？

root@OpenWrt:~# dig ss06.8ke.co +trace

; <<>> DiG 9.9.4 <<>> ss06.8ke.co +trace
;; global options: +cmd
.                       311777  IN      NS      c.root-servers.net..
311777  IN      NS      i.root-servers.net..                       311777
IN      NS      e.root-servers.net..                       311777  IN
NS      b.root-servers.net..                       311777  IN      NS
a.root-servers.net..                       311777  IN      NS
j.root-servers.net..                       311777  IN      NS
h.root-servers.net..                       311777  IN      NS
l.root-servers.net..                       311777  IN      NS
f.root-servers.net..                       311777  IN      NS
g.root-servers.net..                       311777  IN      NS
k.root-servers.net..                       311777  IN      NS
d.root-servers.net..                       311777  IN      NS
m.root-servers.net.;; Received 239 bytes from 127.0.0.1#53(127.0.0.1) in
159 ms

co.                     172800  IN      NS      ns4.cctld.co.
co.                     172800  IN      NS      ns1.cctld.co.
co.                     172800  IN      NS      ns3.cctld.co.
co.                     172800  IN      NS      ns5.cctld.co.
co.                     172800  IN      NS      ns2.cctld.co.
co.                     172800  IN      NS      ns6.cctld.co.
co.                     86400   IN      DS      53851 8 1
C657A15BB7DB976EA26019E87B9FA264F1338286
co.                     86400   IN      DS      53851 8 2
1CD67D439868C9E37694A3EBD5380512822823BC46BA75CBEEB58DAB 7973EA21
co.                     86400   IN      RRSIG   DS 8 1 86400 20150223050000
20150213040000 16665 .
omSARnZ1onz4yBPTxhKRwXkh6AzYoY8X1GqUWNkOVAUtfcQSd/q8FYx2
Bk7BXFB3aY1tUyqYOj987IAj/ENnzBpZasYfAHMo0QnVJuQ38vWRpsto
Dtb4LZ62NMO08oUSApN7SNM6cuNbW6apy1B8/4uf+harSQpJELxFMGUs E+g=
;; Received 661 bytes from 199.7.91.13#53(d.root-servers.net) in 375 ms

8KE.co.                 7200    IN      NS      NS2.360WZB.COM.
8KE.co.                 7200    IN      NS      NS1.360WZB.COM.
8KE.co.                 86400   IN      NSEC    8KEZCIUWLINE.co. NS RRSIG
NSEC
8KE.co.                 86400   IN      RRSIG   NSEC 8 2 86400
20150310024255 20150208022609 37560 co.
VKSpqYwfxXC9/YDmZ6c/n8LhRBl0PWc6EPZORFt6ceB41L6Cl8Hj4Usb
CrccfJwXq6MdjTAX1tgyV2MvXsuD5tPSCYARj5BoZis3r92ua5scXQbK
CXr4wYz0kwoOa7ySQWOfo6Py4yy/KJ2QkcbPcU96KhDQt5qS1hLYuSfI 9N0=
;; Received 289 bytes from 156.154.101.25#53(ns2.cctld.co) in 1497 ms

ss06.8ke.co.            600     IN      A       103.226.125.101
ss06.8ke.co.            600     IN      A       207.226.143.34
ss06.8ke.co.            600     IN      A       118.193.150.214
8ke.co.                 6000    IN      NS      ns2.360wzb.com.
8ke.co.                 6000    IN      NS      ns1.360wzb.com.
;; Received 144 bytes from 180.153.235.242#53(NS2.360WZB.COM) in 127 ms
 2015年2月13日 上午10:53于 "Rin Satsuki" <notifications@github.com>写道：

**Comment by isbaseby** [comment]
可以确定是chinadns的问题，关闭chinadns并恢复dnsmasq默认配置后就可以正常解析。
2015年2月13日 上午10:53于 "Rin Satsuki" <notifications@github.com>写道：

**Comment by aa65535** [comment]
不要通过dnsmasq 查询，直接使用 -p 参数指定到 ChinaDNS 端口，使用 -v 参数查看日志排查。

**Comment by isbaseby** [comment]
/usr/bin/chinadns -p 5353 -s 114.114.114.114,8.8.4.4 -l
/etc/chinadns_iplist.txt -c /etc/chinadns_chnroute.txt -y 0.3 -d

这样，还是无法解决
2015年2月13日 下午9:24于 "Rin Satsuki" <notifications@github.com>写道：
