### ISSUE TITLE
chinadns cannot bind port successfully

### ISSUE THREAD

**Issue by shuosiw** [aa65535/openwrt-chinadns#115]
> ChinaDNS - 1.3.3-1                                                                                                                                                                                         > luci-app-chinadns - 1.6.2-1
> route firmware: OpenWrt v2.7 By stones r6132-c6e0c02d75 / LuCI Master (git-18.023.74248-ee409b6)
> route: phicomm k3

after install chinadns and luci-app, then configure and start.
it look like the process is started when i use ps command:

```
# ps | grep china
19652 root       812 S<   /usr/bin/chinadns -m -b 0.0.0.0 -p 5353 -s 114.114.114.114,8.8.4.4 -c /etc/chinadns_chnroute.txt
```

but it cannot bind port successfully. i cannot find 5353 port in netstat command output:

```
netstat -nlpt | grep 5353
```

when i use `strace` command to debug. it seem cannot get time?

```
# strace -p 19652                                                                                                                                                 strace: Process 19652 attached
clock_gettime(CLOCK_REALTIME, {tv_sec=1585984347, tv_nsec=520622481}) = 0
_newselect(5, [3 4], NULL, [3 4], {tv_sec=0, tv_usec=50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {tv_sec=1585984347, tv_nsec=580634963}) = 0
_newselect(5, [3 4], NULL, [3 4], {tv_sec=0, tv_usec=50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {tv_sec=1585984347, tv_nsec=640658613}) = 0
_newselect(5, [3 4], NULL, [3 4], {tv_sec=0, tv_usec=50000}) = 0 (Timeout)
clock_gettime(CLOCK_REALTIME, {tv_sec=1585984347, tv_nsec=700750609}) = 0
_newselect(5, [3 4], NULL, [3 4], {tv_sec=0, tv_usec=50000}^Cstrace: Process 19652 detached
```

is anyone know this? please help!

**Comment by xujiyong** [comment]
netstat -nlptu | grep 5353

**Comment by shuosiw** [comment]
@xujiyong It's my problem. does not notice the service just use udp protocol. thanks
