### ISSUE TITLE
WNDR 4300 安装 1.31 提示如下,请问是什么原因呢?

### ISSUE THREAD

**Issue by iJayscn** [aa65535/openwrt-chinadns#13]
//usr/lib/opkg/info/bind-libs.postinst: line 4: default_postinst: not found
Collected errors:
 * pkg_run_script: package "bind-libs" postinst script returned status 127.
 * opkg_configure: bind-libs.postinst returned 127.

**Comment by aa65535** [comment]
更新你的 base-files，或者参考 aa65535/openwrt-dnsmasq#3
