### ISSUE TITLE
使用一段时间后只有国内 DNS 在工作

### ISSUE THREAD

**Issue by 4ft35t** [aa65535/openwrt-chinadns#14]
版本：ChinaDNS_1.3.1-1_ramips_24kec.ipk	
设置 DNS 为 114.114.114.114 和 ss 转发的 127.0.0.1:5353，无论是开启延时还是压缩，大概 2-3 分钟后，日志里就只剩下 114 在活跃，127 在日志里完全看不到，境外域名无法解析。重启 chinadns 就好了。

**Comment by cielpy** [comment]
似乎也遇到这个问题了，国内的网站可以正常解析，国外的不行，看浏览器显示正在解析，然后就显示DNS错误，我的是在中继的路由器上部署的ChinaDNS。

**Comment by cielpy** [comment]
似乎我在主路由上部署的ChinaDNS也碰到了这个问题，有时候一直显示正在解析主机，然后重启ChinaDNS就好了。@aa65535

**Comment by isbaseby** [comment]
同样遇到这个问题，并且重启之后马上又会无法解析国外网站

**Comment by xcjiang** [comment]
以前一直是好的，但从今天早上开始，莫名也出现了这样的问题。表现是国内域名OK，国外域名全不行。重启chinadns后恢复正常，但一两个小时候又再次出现异常。
我的配置是国内dns是114，国外通过ss转发udp到8.8.4.4。感觉出现问题时像是udp出不去了，但此时ss应该是没有问题的，因为我只重启chinadns就又OK了，ss压根没动。

**Comment by destinyyun** [comment]
如何指定某一个网站不通过ss代理，比如微软官网，我用的是日本的节点，然后一直给我显示日本微软官网。并且bing地图也直接定位到了日本

**Comment by aa65535** [comment]
这个问题基本是因为 ChinaDNS 上游服务器不稳定导致的。

@destinyyun 
不需要使用 ChinaDNS 查询的域名可以在 dnsmasq 中设置
类似 `server=/.microsoft.com/114.114.114.114` 的规则就行了。

**Comment by destinyyun** [comment]
好的知道了，thanksSent from my Huawei Mobile

**Comment by xcjiang** [comment]
问题关闭了吗，但问题确实存在啊，而且单单重启chindns就好了，屡试不爽，这无法用上游服务器的问题来解释吧，一次两次还有可能是巧合，但次次都是如此就说不通了。

**Comment by riaqn** [comment]
我也可以确认这个问题的存在. 
启动参数:
```
chinadns -c /usr/share/chnroute.txt -l /usr/share/iplist.txt -v -s 223.5.5.5,8.8.8.8
```
`dig @8.8.8.8 google.com`没有问题.
`dig google.com`卡住.
log显示的信息都是223.5.5.5的,没有8.8.8.8的.
重启chinadns就可以解决.

**Comment by ohyeah521** [comment]
我也遇到这样的情况，刚开始用非常好用，然后突然某一天就会这样，重启路由就好了。症状就是所有国内的IP都能正常解析，国外的都不能解析，注意，是不能够解析，不是被投毒。

**Comment by hellorocky** [comment]
遇到了相同的情况

**Comment by joysky77** [comment]
遇到同样的问题，这个问题解决了吗？

**Comment by zhEdward** [comment]
目前还存在 mark

**Comment by dawncold** [comment]
貌似我也遇到了，但又和各位不太一样，dns-forwarder到8.8.8.8一切正常，但转发到1.1.1.1不正常，在ChinaDNS中把dns-forwarder配置成信任DNS后转发到1.1.1.1就正常了，很奇怪。

**Comment by wangxin6** [comment]
@dawncold 同样问题：dns-forwarder到8.8.8.8一切正常，但转发到1.1.1.1不正常。请问如何在ChinaDNS中把dns-forwarder配置成信任DNS？

**Comment by dawncold** [comment]
@wangxin6 配置ChinaDNS时你用“#”代替“:”就表明这个DNS server是个信任DNS，比如我写的127.0.0.1#5300，但仍然有问题，所以我暂时放弃了1.1.1.1，我另一台设备用1.1.1.1没遇到问题，比较奇怪。

@pexcn 这有个详细的问题描述，你看看一样么？https://github.com/aa65535/ChinaDNS/issues/4

**Comment by pexcn** [comment]
我的配置：
ChinaDNS 上游服务器：`119.29.29.29,127.0.0.1:5300` 本地端口：`5353`
ss-tunnel 转发：`1.1.1.1:53` 本地端口：`5300`
路由器 IP: `192.168.1.1`

以下命令测试：
```bash
dig twitter.com @192.168.1.1 -p 5300
# 能正常响应，有结果。

dig twitter.com @192.168.1.1 -p 5353
# 无响应，随后我 Ctrl + C 结束程序。
```

@dawncold 
@aa65535

**Comment by pexcn** [comment]
是不是 ChinaDNS 对 `1.1.1.1` 这个地址的判断有问题？我用的路由表是 https://github.com/pexcn/daily/tree/gh-pages/chnroute

**Comment by aa65535** [comment]
@pexcn ChinaDNS 并没有直接把 `1.1.1.1` 作为上游，所以跟 chnroute 没关系，这个更多的可能在你的网络。

**Comment by pexcn** [comment]
@aa65535 我 VPS 上的网络是可以访问 `1.1.1.1` 的。
dig 转发 1.1.1.1 的 ss-tunnel 的 5300 端口又能响应。

```bash
当 119.29.29.29,127.0.0.1:5300 ( --> 8.8.8.8) 时，# 国内DNS，国外DNS
当 119.29.29.29,127.0.0.1:5300 ( --> 1.1.1.1) 时，# 都被判断成国内DNS
```
难道不是以上这样吗？

**Comment by wangxin6** [comment]
我目前的情况和上面两位情况一样。1.1.1.1在路由器重启以后可以用一段时间。然后就会发生只有国内网站可以访问的情况。

解决方案：或者换8.8.8.8，或者保持1.1.11不变重启路由器。

**Comment by dawncold** [comment]
@aa65535 如果是网络问题，那么应该无论怎样都用不了1.1.1.1才对。因为直接dig用`1.1.1.1`和dig用dns-forwarder，甚至把dns-forwarder改为信任DNS都是可以的，唯独作为国外DNS时ChinaDNS得不到结果

**Comment by dawncold** [comment]
@pexcn 我关闭了ChinaDNS的压缩指针功能（去掉-m参数），觉得正常了，你可以试试看。

**Comment by pexcn** [comment]
还是用 `8.8.8.8` 了，在我 VPS 上访问 `8.8.8.8` 比 `1.1.1.1` 延迟还低...
