### ISSUE TITLE
关于53端口的转发

### ISSUE THREAD

**Issue by houzi-** [aa65535/openwrt-chinadns#15]
您好！
我看到官方的init脚本里面有这个重定向规则，而openwrt面却没有！
```shell
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5353
```
请问这个跟server=127.0.0.1#5353一样？所以就没必要再转发？

**Comment by 70599** [comment]
你使用正常就没必要转发。二者二选其一。推荐使用server=

**Comment by aa65535** [comment]
作为 dnsmasq 的上游服务器就不需要 iptables  规则。
