### ISSUE TITLE
一直显示未运行

### ISSUE THREAD

**Issue by wangxj-nemo** [aa65535/openwrt-chinadns#16]
/etc/init.d/chinadns enable,start ,restart都试过了，luci界面里面一直是未运行，而且ps里面也没有chinadns的进程，用的是最新的1.3.1-1版本，luci也是1.3.1-1的，第一次安装的时候可以，后来就不行了，本地端口也试了没被占用的端口，如何调试从而发现原因？

**Comment by wangxj-nemo** [comment]
测试发现chinadns启动后3，4秒即死掉了，
 3586 root       844 S    /usr/bin/chinadns -p 5555 -s 114.114.114.114,***.***.***:****-c /etc/shadowsocks/ignore.list -m
无论用114,还是本地ISP的DNS都是这样，***是个人私有DNS服务器，dig无问题。

似乎是内存不够用挂掉，但是内存还有很多，WNDR3800

内存
可用数	
104024 kB / 126324 kB (82%)
空闲数	
91644 kB / 126324 kB (72%)
已缓存	
10196 kB / 126324 kB (8%)
已缓冲	
2184 kB / 126324 kB (1%)

**Comment by 70599** [comment]
ignore.list文件正常吗？

**Comment by wangxj-nemo** [comment]
正常这么解释？不正常又怎么解释？

**Comment by 70599** [comment]
1、是不是空的
2、有没有IP地址以外格式的文字
3、chinadns启动命令的引用路径是否正确

**Comment by wangxj-nemo** [comment]
3的问题肯定不会有，不然也不会启动3，4秒；1，2查了，也没有问题，我都是在VPS上WGET得到完整的list,然后拖到本地windows系统下，然后从windows系统拖到路由器，一直这么弄的，肯定也不是dos，unix编码的问题。

**Comment by 70599** [comment]
“一直这么弄的”
意思是以前正常，后来不正常了吗？
是的话回忆一下你都做过什么吧。
我这里一切正常，所以应该不是程序的问题，是你自己环境的问题，也没有别的能想到要排查的问题了。

**Comment by wangxj-nemo** [comment]
这，，，好吧，还是谢谢你的解答

**Comment by aa65535** [comment]
可以加上 `-v` 参数后手动执行 chinadns ，看一下发生了什么错误。

**Comment by wangxj-nemo** [comment]
谢谢，这个回复说到点子上了
