### ISSUE TITLE
返回IP都合法优先取用国外IP

### ISSUE THREAD

**Issue by Phishion** [aa65535/openwrt-chinadns#17]
我发现了一个奇怪的现象，我这边设置114.114.114.114+8.8.8.8的时候，dig淘宝网知道取用国内的地址，设置成114.114.114.114+127.0.0.1:5353（pdnsd）的时候，优先取用的是pdnsd返回的国外地址，为什么会有这样的情况？@aa65535

**Comment by aa65535** [comment]
大概是因为 pdnsd 有缓存吧，然后导致 pdnsd 返回的结果比 114DNS 更快，于是就直接取用 pdnsd 的结果了。

**Comment by qwIvan** [comment]
我也遇到同样问题。由于pdnsd有缓存，所以它查询速度比114要快。每次都拿pdnsd的查询结果而非114的结果。当两个查询结果都合法时，有没有办法让国内结果优先于国外呢？
