### ISSUE TITLE
chinadns到底需要怎么设置？

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-chinadns#19]
被搞晕了。
更新到最新版，和luci最新版，从这下载更新的。

运行后，ps能看到：/usr/bin/chinadns -p 5353 -s 114.114.114.114,8.8.4.4 -c /etc/china_ip_list.txt -d -m

但是youtube域名就是解析不了。我kill掉进程，手工运行：
/usr/bin/chinadns -p 5353 -s 114.114.114.114,8.8.4.4 -c /etc/china_ip_list.txt -d -m -v

发现访问youtube.com，没有任何信息输出，我记得以前版本用-v参数可以看到实时的域名处理信息的。

chinadns除了在自己的luci界面上设置，还需要其他地方设置吗。
百度看了，有的人是设置到dhcp/dns的dns转发，地址写：127.0.0.0.1#5353 我也设置了，都没效果。

哎，真怎么就没有一个准确点的说明呢

**Comment by aa65535** [comment]
`/etc/china_ip_list.txt` 文件里面是什么内容？
`cat /var/etc/dnsmasq.conf` 命令的打印内容是什么？

检查DNS解析使用 `dig youtube.com -p 5353`

**Comment by hdstar2009** [comment]
/etc/china_ip_list.txt 是国内路由表
然后我到dhcp/dns设置页面把本地服务器设置为了chinadns的127.0.0.1#5353，在「HOSTS和解析文件」勾选 *忽略解析文件
了。目前翻墙正常。*


*晕，我想说的是，chinadns包括shadowsocks的luci设置页面能出个说明也好啊。*



2015-08-19 21:48 GMT+08:00 Jian Chang <notifications@github.com>:
