### ISSUE TITLE
通过源更新到1.3.2后，不能通过非标准端口的上游DNS Server查询DNS记录

### ISSUE THREAD

**Issue by niclau** [aa65535/openwrt-chinadns#20]
dig twitter.com @127.0.0.1 -p 5353

; <<>> DiG 9.9.4 <<>> twitter.com @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by aa65535** [comment]
请提供启动时的命令行参数，以及运行日志。

**Comment by niclau** [comment]
@aa65535 再次安装后已正常使用。
