### ISSUE TITLE
使用SS提供的UDP转发解析失败？

### ISSUE THREAD

**Issue by suikatomoki** [aa65535/openwrt-chinadns#21]
root@OpenWrt:~# dig www.bing.com @127.0.0.1 -p 5353

; <<>> DiG 9.9.4 <<>> www.bing.com @127.0.0.1 -p 5353
;; global options: +cmd
;; connection timed out; no servers could be reached
root@OpenWrt:~#

直接dig www.bing.com @127.0.0.1 -p 5300
无异常 正常解析

5300端口是ss的udp查询
5353端口是chinadns的上游服务器第二条记录你懂的，第一条是114.114.114.114

**Comment by suikatomoki** [comment]
噗，5353是chinadns的端口，他的的上游服务器第二条记录是5300，第一条是114.114.114.114

**Comment by suikatomoki** [comment]
ss那边转发用的是8.8.8.8:53

**Comment by aa65535** [comment]
ChinaDNS 有正常启动？
可以加上 `-v` 参数启动后看一下日志。

**Comment by AttufliX** [comment]
这个问题我也遇到了, 我在pc的chinadns上也遇到同样的问题，表现为刚打开chinadns可以解析正确，之后到ss的udp转发就没有响应了

**Comment by suikatomoki** [comment]
看了一下日志，什么request win10.ipv6.microsoft.com，纳尼，怎么搞到ipv6那里去了，我ss服务器和本地宽带都是ipv4的啊

**Comment by suikatomoki** [comment]
是这样启动没错吧
/usr/bin/chinadns -p 5353 -s 114.114.114.114,127.0.0.1:5300 -c /etc/shadowsocks/ignore.list -v >> /var/log/3

日志内容:访问了baidu和facebook后
Sun Aug 23 04:11:00 2015 request sp1.baidu.com
Sun Aug 23 04:11:00 2015 response sp1.baidu.com from 114.114.114.114:53 - 61.135.169.125, 61.135.169.121, pass
Sun Aug 23 04:11:01 2015 request sp2.baidu.com
Sun Aug 23 04:11:01 2015 response sp2.baidu.com from 114.114.114.114:53 - 61.135.169.121, 61.135.169.125, pass
Sun Aug 23 04:11:01 2015 request tieba.baidu.com
Sun Aug 23 04:11:01 2015 response tieba.baidu.com from 114.114.114.114:53 - 180.97.33.24, 180.97.33.23, pass
Sun Aug 23 04:11:02 2015 request tb1.bdstatic.com
Sun Aug 23 04:11:02 2015 response tb1.bdstatic.com from 114.114.114.114:53 - 112.65.203.48, pass
Sun Aug 23 04:11:02 2015 request tb2.bdstatic.com
Sun Aug 23 04:11:02 2015 response tb2.bdstatic.com from 114.114.114.114:53 - 112.65.203.48, pass
Sun Aug 23 04:11:04 2015 request imgsrc.baidu.com
Sun Aug 23 04:11:04 2015 request youxi.baidu.com
Sun Aug 23 04:11:04 2015 request image.cache.xiu8.com
Sun Aug 23 04:11:04 2015 response imgsrc.baidu.com from 114.114.114.114:53 - 112.65.203.48, pass
Sun Aug 23 04:11:04 2015 response youxi.baidu.com from 114.114.114.114:53 - 123.125.114.89, pass
Sun Aug 23 04:11:04 2015 response image.cache.xiu8.com from 114.114.114.114:53 - 119.188.138.24, 119.188.138.29, pass
Sun Aug 23 04:11:05 2015 request play.baidu.com
Sun Aug 23 04:11:05 2015 response play.baidu.com from 114.114.114.114:53 - 123.125.114.14, 123.125.115.20, pass
Sun Aug 23 04:11:07 2015 request www.malwaredomainlist.com
Sun Aug 23 04:11:07 2015 response www.malwaredomainlist.com from 114.114.114.114:53 - 143.215.130.61, filter
Sun Aug 23 04:11:08 2015 request message.tieba.baidu.com
Sun Aug 23 04:11:08 2015 response message.tieba.baidu.com from 114.114.114.114:53 - 123.125.65.210, pass
Sun Aug 23 04:11:08 2015 request www.malwaredomainlist.com
Sun Aug 23 04:11:09 2015 response www.malwaredomainlist.com from 114.114.114.114:53 - 143.215.130.61, filter
Sun Aug 23 04:11:09 2015 request tb.himg.baidu.com
Sun Aug 23 04:11:09 2015 response tb.himg.baidu.com from 114.114.114.114:53 - 112.65.203.48, pass
Sun Aug 23 04:11:09 2015 request d.hiphotos.baidu.com
Sun Aug 23 04:11:09 2015 response d.hiphotos.baidu.com from 114.114.114.114:53 - 112.65.203.48, pass
Sun Aug 23 04:11:10 2015 request b.hiphotos.baidu.com
Sun Aug 23 04:11:10 2015 response b.hiphotos.baidu.com from 114.114.114.114:53 - 112.65.203.48, pass
Sun Aug 23 04:11:10 2015 request www.malwaredomainlist.com
Sun Aug 23 04:11:10 2015 response www.malwaredomainlist.com from 114.114.114.114:53 - 143.215.130.61, filter
Sun Aug 23 04:11:11 2015 request static.tieba.baidu.com
Sun Aug 23 04:11:11 2015 response static.tieba.baidu.com from 114.114.114.114:53 - 61.135.185.139, pass
Sun Aug 23 04:11:14 2015 request www.malwaredomainlist.com
Sun Aug 23 04:11:14 2015 response www.malwaredomainlist.com from 114.114.114.114:53 - 143.215.130.61, filter
Sun Aug 23 04:11:33 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:33 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 63.130.76.82, filter
Sun Aug 23 04:11:34 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:34 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 209.107.203.27, filter
Sun Aug 23 04:11:36 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:36 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 209.107.203.66, filter
Sun Aug 23 04:11:40 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:40 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 209.107.203.27, filter
Sun Aug 23 04:11:44 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:44 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 23.62.109.145, filter
Sun Aug 23 04:11:45 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:45 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 23.62.109.136, filter
Sun Aug 23 04:11:47 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:47 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 - 23.62.109.145, filter
Sun Aug 23 04:11:51 2015 request fbstatic-a.akamaihd.net
Sun Aug 23 04:11:51 2015 response fbstatic-a.akamaihd.net from 114.114.114.114:53 -

**Comment by suikatomoki** [comment]
国内的网站好像都可以正常解析，其他的都不行

**Comment by suikatomoki** [comment]
WTF ...
使用了参数启动后，得到了上面那些不正常的日志，最后我终止了启动，打开了路由器chinadns的设置界面并启动它。然后我惊喜的发现变正常了，可以正常解析了。随后我继续使用了参数启动观看了一下日志：

发现没什么异常 127.0.0.1:5300  这条终于出现了
72.14.247.65, pass
Sun Aug 23 04:24:54 2015 request www.baidu.com
Sun Aug 23 04:24:54 2015 response www.baidu.com from 114.114.114.114:53 - 61.135.169.125, 61.135.169.121, pass
Sun Aug 23 04:24:55 2015 response www.baidu.com from 127.0.0.1:5300 - 115.239.210.27, 115.239.211.112, pass
Sun Aug 23 04:24:55 2015 request sp0.baidu.com
Sun Aug 23 04:24:55 2015 response sp0.baidu.com from 114.114.114.114:53 - 61.135.169.121, 61.135.169.125, pass
Sun Aug 23 04:24:56 2015 request formi.baidu.com
Sun Aug 23 04:24:56 2015 response formi.baidu.com from 114.114.114.114:53 - 180.149.131.55, 61.135.169.120, pass
Sun Aug 23 04:24:56 2015 response formi.baidu.com from 127.0.0.1:5300 - 180.149.131.55, 61.135.169.120, pass
Sun Aug 23 04:24:57 2015 response sp0.baidu.com from 127.0.0.1:5300 - 115.239.210.27, 115.239.211.112, pass
Sun Aug 23 04:24:57 2015 request ss0.baidu.com
Sun Aug 23 04:24:57 2015 request ss1.baidu.com
Sun Aug 23 04:24:57 2015 request ss2.baidu.com
Sun Aug 23 04:24:57 2015 request ss3.baidu.com
Sun Aug 23 04:24:57 2015 response ss0.baidu.com from 114.114.114.114:53 - 112.65.203.33, pass
Sun Aug 23 04:24:57 2015 response ss1.baidu.com from 114.114.114.114:53 - 112.65.203.33, pass
Sun Aug 23 04:24:57 2015 response ss2.baidu.com from 114.114.114.114:53 - 112.65.203.33, pass
Sun Aug 23 04:24:57 2015 response ss3.baidu.com from 114.114.114.114:53 - 112.65.203.33, pass
Sun Aug 23 04:24:58 2015 response ss2.baidu.com from 127.0.0.1:5300 - 111.206.76.33, pass
Sun Aug 23 04:24:58 2015 response ss0.baidu.com from 127.0.0.1:5300 - 111.206.76.33, pass
Sun Aug 23 04:24:58 2015 response ss1.baidu.com from 127.0.0.1:5300 - 111.206.76.33, pass
Sun Aug 23 04:24:58 2015 response ss3.baidu.com from 127.0.0.1:5300 - 111.206.76.33, pass
Sun Aug 23 04:24:59 2015 request ss2.bdstatic.com
Sun Aug 23 04:24:59 2015 request sp1.baidu.com
Sun Aug 23 04:25:00 2015 response ss2.bdstatic.com from 127.0.0.1:5300 - 111.206.76.32, pass
Sun Aug 23 04:25:00 2015 response ss2.bdstatic.com from 114.114.114.114:53 - 111.206.76.32, pass
Sun Aug 23 04:25:00 2015 response sp1.baidu.com from 127.0.0.1:5300 - 115.239.210.27, 115.239.211.112, pass
Sun Aug 23 04:25:00 2015 response sp1.baidu.com from 114.114.114.114:53 -

**Comment by suikatomoki** [comment]
把路由器重启了一下，没什么问题，可以正常使用，看来这个问题我已经无法重现了，总结一下就是：某一天我突然发现我之前用的好好的chinadns突然罢工了，只能解析国内的那些域名，然后我在路由器管理界面卸载并重装了chinadns，发现没什么卵用。之后我把路由器格了重装了一下系统，然后再把ss和chinadns那套装起来了，发现还是没什么卵用。接着我就来到这里反馈了，之后的情况就是上面那些回复内容了。

**Comment by suikatomoki** [comment]
唉，又出现这种情况了，又不可以解析国外域名了，只能解析国内域名。

**Comment by suikatomoki** [comment]
Sun Aug 23 14:35:25 2015 request plus.google.com
Sun Aug 23 14:35:25 2015 response plus.google.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:26 2015 request plus.google.com
Sun Aug 23 14:35:26 2015 response plus.google.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:28 2015 request plus.google.com
Sun Aug 23 14:35:28 2015 response plus.google.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:29 2015 request www.youtube.com
Sun Aug 23 14:35:29 2015 response www.youtube.com from 114.114.114.114:53 - 93.46.8.89, filter
Sun Aug 23 14:35:30 2015 request www.youtube.com
Sun Aug 23 14:35:30 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:32 2015 request plus.google.com
Sun Aug 23 14:35:32 2015 request www.youtube.com
Sun Aug 23 14:35:32 2015 response plus.google.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:32 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:36 2015 request www.google.com
Sun Aug 23 14:35:36 2015 request www.youtube.com
Sun Aug 23 14:35:36 2015 response www.google.com from 114.114.114.114:53 - 216.58.221.132, filter
Sun Aug 23 14:35:36 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:38 2015 request www.google.com
Sun Aug 23 14:35:38 2015 response www.google.com from 114.114.114.114:53 - 216.58.221.132, filter
Sun Aug 23 14:35:40 2015 request www.google.com
Sun Aug 23 14:35:40 2015 response www.google.com from 114.114.114.114:53 - 216.58.221.132, filter
Sun Aug 23 14:35:41 2015 request www.youtube.com
Sun Aug 23 14:35:41 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:35:41 2015 request google.com
Sun Aug 23 14:35:42 2015 response google.com from 114.114.114.114:53 - 216.58.221.110, filter
Sun Aug 23 14:35:46 2015 request qq.com
Sun Aug 23 14:35:46 2015 response qq.com from 114.114.114.114:53 - 125.39.240.113, 163.177.65.160, pass
Sun Aug 23 14:35:53 2015 request google.com
Sun Aug 23 14:35:53 2015 response google.com from 114.114.114.114:53 - 216.58.221.110, filter
Sun Aug 23 14:35:58 2015 request www.youtube.com
Sun Aug 23 14:35:58 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:36:01 2015 request www.youtube.com
Sun Aug 23 14:36:01 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:36:05 2015 request www.youtube.com
Sun Aug 23 14:36:05 2015 response www.youtube.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:36:10 2015 request google.com
Sun Aug 23 14:36:10 2015 response google.com from 114.114.114.114:53 - Sun Aug 23 14:36:25 2015 request dict.youdao.com
Sun Aug 23 14:36:25 2015 response dict.youdao.com from 114.114.114.114:53 - 61.135.217.78, 61.135.217.79, 61.135.218.10, 61.135.218.44, 61.135.218.45, 61.135.218.46, 61.135.218.47, 61.135.218.48, 61.135.218.71, 61.135.217.77, pass
Sun Aug 23 14:36:26 2015 request oimagea8.ydstatic.com
Sun Aug 23 14:36:26 2015 response oimagea8.ydstatic.com from 114.114.114.114:53 - 60.212.19.154, 218.59.213.136, pass
Sun Aug 23 14:36:28 2015 request plus.google.com
Sun Aug 23 14:36:28 2015 response plus.google.com from 114.114.114.114:53 - 159.106.121.75, filter
Sun Aug 23 14:36:30 2015 request play.google.com
Sun Aug 23 14:36:30 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:36:31 2015 request plus.google.com
Sun Aug 23 14:36:31 2015 response plus.google.com from 114.114.114.114:53 - 8.7.198.45, filter
Sun Aug 23 14:36:33 2015 request play.google.com
Sun Aug 23 14:36:33 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:36:35 2015 request plus.google.com
Sun Aug 23 14:36:35 2015 response plus.google.com from 114.114.114.114:53 - 8.7.198.45, filter
Sun Aug 23 14:36:37 2015 request play.google.com
Sun Aug 23 14:36:37 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:36:41 2015 request play.google.com
Sun Aug 23 14:36:41 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:36:42 2015 request google.com
Sun Aug 23 14:36:42 2015 response google.com from 114.114.114.114:53 - 216.58.221.110, filter
Sun Aug 23 14:36:44 2015 request play.google.com
Sun Aug 23 14:36:44 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.46, filter
Sun Aug 23 14:36:48 2015 request play.google.com
Sun Aug 23 14:36:48 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.46, filter
Sun Aug 23 14:36:53 2015 request google.com
Sun Aug 23 14:36:53 2015 response google.com from 114.114.114.114:53 - 216.58.221.110, filter
Sun Aug 23 14:36:58 2015 request play.google.com
Sun Aug 23 14:36:58 2015 response play.google.com from 114.114.114.114:53 - 216.58.221.46, filter
Sun Aug 23 14:36:58 2015 response play.google.com from 127.0.0.1:5300 - 74.125.224.40, 74.125.224.36, 74.125.224.41, 74.125.224.32, 74.125.224.39, 74.125.224.38, 74.125.224.34, 74.125.224.33, 74.125.224.46, 74.125.224.35, 74.125.224.37, pass
Sun Aug 23 14:37:02 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:02 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:02 2015 request lh4.ggpht.com
Sun Aug 23 14:37:02 2015 request lh6.ggpht.com
Sun Aug 23 14:37:02 2015 response lh4.ggpht.com from 114.114.114.114:53 - 216.58.221.33, filter
Sun Aug 23 14:37:02 2015 response lh6.ggpht.com from 114.114.114.114:53 - 216.58.221.65, filter
Sun Aug 23 14:37:02 2015 request lh3.ggpht.com
Sun Aug 23 14:37:02 2015 response lh3.ggpht.com from 114.114.114.114:53 - 216.58.221.97, filter
Sun Aug 23 14:37:04 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:04 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:05 2015 request lh4.ggpht.com
Sun Aug 23 14:37:05 2015 request lh6.ggpht.com
Sun Aug 23 14:37:05 2015 response lh4.ggpht.com from 114.114.114.114:53 - 216.58.221.33, filter
Sun Aug 23 14:37:05 2015 response lh6.ggpht.com from 114.114.114.114:53 - 216.58.221.65, filter
Sun Aug 23 14:37:05 2015 request lh3.ggpht.com
Sun Aug 23 14:37:05 2015 response lh3.ggpht.com from 114.114.114.114:53 - 216.58.221.97, filter
Sun Aug 23 14:37:09 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:09 2015 request lh4.ggpht.com
Sun Aug 23 14:37:09 2015 request lh6.ggpht.com
Sun Aug 23 14:37:09 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:09 2015 response lh4.ggpht.com from 114.114.114.114:53 - 216.58.221.33, filter
Sun Aug 23 14:37:09 2015 response lh6.ggpht.com from 114.114.114.114:53 - 216.58.221.65, filter
Sun Aug 23 14:37:09 2015 request lh3.ggpht.com
Sun Aug 23 14:37:09 2015 response lh3.ggpht.com from 114.114.114.114:53 - 216.58.221.97, filter
Sun Aug 23 14:37:11 2015 request wallet.google.com
Sun Aug 23 14:37:12 2015 response wallet.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:37:12 2015 request cidian.youdao.com
Sun Aug 23 14:37:12 2015 response cidian.youdao.com from 114.114.114.114:53 - 61.135.217.78, 61.135.218.46, 61.135.218.71, 61.135.217.77, 61.135.218.47, 61.135.218.44, 61.135.217.79, 61.135.218.45, 61.135.218.48, 61.135.218.10, pass
Sun Aug 23 14:37:12 2015 request www.gstatic.com
Sun Aug 23 14:37:12 2015 response www.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:13 2015 request books.google.com
Sun Aug 23 14:37:13 2015 request ssl.gstatic.com
Sun Aug 23 14:37:13 2015 response ssl.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:13 2015 response books.google.com from 114.114.114.114:53 - 74.125.23.102, filter
Sun Aug 23 14:37:13 2015 request wallet.google.com
Sun Aug 23 14:37:13 2015 request lh4.googleusercontent.com
Sun Aug 23 14:37:13 2015 response wallet.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:37:13 2015 response lh4.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:13 2015 request apis.google.com
Sun Aug 23 14:37:13 2015 response apis.google.com from 114.114.114.114:53 - 74.125.203.101, filter
Sun Aug 23 14:37:13 2015 request www.gstatic.com
Sun Aug 23 14:37:14 2015 response www.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:14 2015 request books.google.com
Sun Aug 23 14:37:14 2015 request ssl.gstatic.com
Sun Aug 23 14:37:14 2015 response books.google.com from 114.114.114.114:53 - 74.125.23.138, filter
Sun Aug 23 14:37:14 2015 response ssl.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:15 2015 request wallet.google.com
Sun Aug 23 14:37:15 2015 response wallet.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:37:15 2015 request www.gstatic.com
Sun Aug 23 14:37:16 2015 response www.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:16 2015 request books.google.com
Sun Aug 23 14:37:16 2015 request ssl.gstatic.com
Sun Aug 23 14:37:16 2015 request lh4.googleusercontent.com
Sun Aug 23 14:37:16 2015 response books.google.com from 114.114.114.114:53 - 74.125.23.139, filter
Sun Aug 23 14:37:16 2015 response ssl.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:16 2015 response lh4.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:16 2015 request apis.google.com
Sun Aug 23 14:37:16 2015 response apis.google.com from 114.114.114.114:53 - 74.125.203.102, filter
Sun Aug 23 14:37:19 2015 request wallet.google.com
Sun Aug 23 14:37:19 2015 response wallet.google.com from 114.114.114.114:53 - 216.58.221.78, filter
Sun Aug 23 14:37:19 2015 request www.gstatic.com
Sun Aug 23 14:37:20 2015 response www.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:20 2015 request books.google.com
Sun Aug 23 14:37:20 2015 request ssl.gstatic.com
Sun Aug 23 14:37:20 2015 request lh4.googleusercontent.com
Sun Aug 23 14:37:20 2015 response books.google.com from 114.114.114.114:53 - 74.125.23.100, filter
Sun Aug 23 14:37:20 2015 response ssl.gstatic.com from 114.114.114.114:53 - 216.58.221.131, filter
Sun Aug 23 14:37:20 2015 response lh4.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:20 2015 request apis.google.com
Sun Aug 23 14:37:20 2015 response apis.google.com from 114.114.114.114:53 - 74.125.203.138, filter
Sun Aug 23 14:37:23 2015 request www.codingke.com
Sun Aug 23 14:37:23 2015 response www.codingke.com from 114.114.114.114:53 - 123.56.137.249, delay
Sun Aug 23 14:37:23 2015 request www.youtube.com
Sun Aug 23 14:37:23 2015 response www.youtube.com from 114.114.114.114:53 - 93.46.8.89, filter
Sun Aug 23 14:37:23 2015 request plus.google.com
Sun Aug 23 14:37:24 2015 response plus.google.com from 114.114.114.114:53 - 8.7.198.45, filter
Sun Aug 23 14:37:24 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:24 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:24 2015 request www.youtube.com
Sun Aug 23 14:37:24 2015 response www.youtube.com from 114.114.114.114:53 - 93.46.8.89, filter
Sun Aug 23 14:37:25 2015 request plus.google.com
Sun Aug 23 14:37:25 2015 response plus.google.com from 114.114.114.114:53 - 8.7.198.45, filter
Sun Aug 23 14:37:25 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:25 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:26 2015 request www.youtube.com
Sun Aug 23 14:37:26 2015 response www.youtube.com from 114.114.114.114:53 - 93.46.8.89, filter
Sun Aug 23 14:37:27 2015 request plus.google.com
Sun Aug 23 14:37:27 2015 response plus.google.com from 114.114.114.114:53 - 8.7.198.45, filter
Sun Aug 23 14:37:27 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:27 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:30 2015 request www.youtube.com
Sun Aug 23 14:37:30 2015 response www.youtube.com from 114.114.114.114:53 - 93.46.8.89, filter
Sun Aug 23 14:37:31 2015 request plus.google.com
Sun Aug 23 14:37:31 2015 response plus.google.com from 114.114.114.114:53 - 8.7.198.45, filter
Sun Aug 23 14:37:31 2015 request lh3.googleusercontent.com
Sun Aug 23 14:37:31 2015 response lh3.googleusercontent.com from 114.114.114.114:53 - 216.58.221.129, filter
Sun Aug 23 14:37:34 2015 request www.youtube.com
Sun Aug 23 14:37:34 2015 response www.youtube.com from 114.114.114.114:53 - 93.46.8.89, filter
Sun Aug 23 14:37:35 2015 request google.com
Sun Aug 23 14:37:35 2015 response google.com from 114.114.114.114:53 - 216.58.221.142, filter
Sun Aug 23 14:37:36 2015 request www.youtube.com
Sun Aug 23 14:37:36 2015 response www.youtube.com from 114.114.114.114:53 -

**Comment by aa65535** [comment]
@suikatomoki 
这个情况应该不是 ChinaDNS 的问题，更像是 `127.0.0.1:5300` 无响应，
出问题时，有试过 `127.0.0.1:5300` 是否可用吗？

**Comment by suikatomoki** [comment]
是的，我也觉得很奇怪，容我再用几天多试试

**Comment by xcjiang** [comment]
这问题已经很久了： https://github.com/aa65535/openwrt-chinadns/issues/14

**Comment by suikatomoki** [comment]
@xcjiang 
是的，日常抽风

**Comment by cokebar** [comment]
@aa65535 应该不是127.0.0.1:5300无响应 我几个月之前遇到过 当时测试的比较详细
直接访问远端DNS 正常
通过ss-tunnel 正常
但是通过chinadns 就能访问一小段时间 然后国外的就再也没反应了
那一段时间我在路由器上有加了一级pdnsd，然后：client发起国外域名查询->dnsmasq->chinadns->pdnsd->远端DNS服务器，这样来的，用的是UDP，没有用TCP，然后就稳定了
记得那一段issue都在讨论一个 transaction ID（好像是这个名字吧）的bug，我想是不是因为ID对不上了导致一直没反应的。难道gfw会修改id号了？

**Comment by imsuwj** [comment]
@aa65535 我也遇到这个问题，并且很频繁。不是127.0.0.1:5300无响应，因为`dig @192.168.1.1 google.com -p 5300`，可以准确返回结果，而`dig @192.168.1.1 google.com -p 5353`结果是`;; connection timed out; no servers could be reached`

**Comment by ohyeah521** [comment]
@suikatomoki   我也遇到这个问题，目前的解决办法是每隔一个小时重启一次chinadns服务，再计划任务里面添加  /etc/init.d/chinadns  restart

**Comment by suikatomoki** [comment]
@ohyeah521 我在SS与ChinaDns之间加了层pdnsd，把解析结果长时间缓存起来。然后又把Dnsmasq换成了aa65535的修改版，把能从ChinaDns那里解析到的结果再长时间缓存起来。效果拔群！

**Comment by ohyeah521** [comment]
pdnsd 这个我之前也用过，效果不错，唯一的缺点就是占用内存太多，如果你是linksys wrt1900ac这样配置的路由器还是可以这样玩的。配置低的跑不动。

**Comment by suikatomoki** [comment]
@ohyeah521 还行吧，我用的是wndr4300，应该没问题的

**Comment by zjufrankzhang** [comment]
@imsuwj 我昨天也碰到了你说的chinadns挂掉而127.0.0.1:5300正常的事件了，看来不是个例呀。就是dig 5353长时间无反应，在luci界面重启chinadns后问题消失
运行环境：newifi y1刷的openwrt 自行编译的15.05稳定版（非trunk），不过内核是3.18.21

**Comment by 4ft35t** [comment]
这个问题由来已久，能否把检测上游的机制去掉？我现在的解决方案是 crontab 每分钟检查一次，解析不了国外域名就重启 chinadns。

**Comment by kaktos** [comment]
同遇到该问题，我配置了114.114.114.114和国外自建服务器，加上`-v`后发现，只有第一次国内国外DNS 有解析，后面就只有114.114.114.114的结果返回了。

**Comment by moondigi** [comment]
关注，同样遇到这种问题，只能重启chinadns

**Comment by suikatomoki** [comment]
@moondigi 

server=/.bilibili.com/114.114.114.114#53
server=/.acg.tv/114.114.114.114#53
server=/.acgvideo.com/114.114.114.114#53
server=/.hdslb.com/114.114.114.114#53
server=/.hdslb.net/114.114.114.114#53

目前只能这样了

**Comment by cokebar** [comment]
@suikatomoki @moondigi  CDN问题 可以试试chinalist
https://github.com/felixonmars/dnsmasq-china-list

**Comment by ohyeah521** [comment]
如果chinadns可以支持域名黑名单就好了，只让黑名单中的域名走海外的dns，其他的走国内的dns，这样就完美了。

**Comment by cokebar** [comment]
@ohyeah521 你说的这功能dnsmasq即可

**Comment by suikatomoki** [comment]
@cokebar 

有个问题，chinadns只能通过udp查询国内公共dns吗？我可以tcp+114dns查询吗？

我的想法就是加层pdnsd监听在54端口强制走114dns的tcp查询，然后chinsdns的上游服务器填写127.0.0.1:54,127.0.0.1:5300。但是这样chinadns会把54端口的dns识别为可信的dns（使用 # 分开 ip 和 port 的DNS服务器即被认为是可信DNS）。导致我的想法不能实现我正确的效果。

**Comment by zixia** [comment]
我这里的现象是同样的配置，在有一些宽带的环境中，ss-tunnel的dns解析无法成功。换tcp dns之后就没问题了。

**Comment by 6donote4** [comment]
走”ss-tunnel” 解析成功，
不将dnsmasq设置为转发到ChinaDns,而是设置”ss-tunnel”, 作为上游服务，分别dig Chinadns, 和53端口，国内国外均可解析成功。
但将dnsmasq上游服务器设为Chinadns 之后，国内，国外均解析失败。
结论：Chinadns返回结果给dnsmasq的过程存在问题。
