### ISSUE TITLE
1.3.2-1版本无法返回结果

### ISSUE THREAD

**Issue by SuZixiong** [aa65535/openwrt-chinadns#23]
我的ChinaDNS版本为1.3.2-1，症状为在国内加速列表accelerated-domains.china.conf和国外 foreign_list.conf 这两个列表外的域名会出现ERR_NAME_NOT_RESOLVED。
----------------------------------------------------------------------
digChinaDNS信息如下，没有返回结果，

C:\Users\szx42>dig @192.168.1.1 -p 35353 interfacelift.com

; <<>> DiG 9.10.2-P4 <<>> @192.168.1.1 -p 35353 interfacelift.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 55980
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; QUESTION SECTION:
;interfacelift.com.             IN      A

;; Query time: 195 msec
;; SERVER: 192.168.1.1#35353(192.168.1.1)
;; WHEN: Thu Sep 03 17:03:13 ?D1ú±ê×?ê±?? 2015
;; MSG SIZE  rcvd: 36

----------------------------------------------------------------------

dig远端非标dns服务器如下，返回正常，

C:\Users\szx42>dig @*.*.*.*  -p 5050 interfacelift.com

; <<>> DiG 9.10.2-P4 <<>> @*.*.*.* -p 5050 interfacelift.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39281
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;interfacelift.com.             IN      A

;; ANSWER SECTION:
interfacelift.com.      900     IN      A       206.190.152.82

;; Query time: 275 msec
;; SERVER: 192.243.118.182#5050(192.243.118.182)
;; WHEN: Thu Sep 03 17:03:29 ?D1ú±ê×?ê±?? 2015
;; MSG SIZE  rcvd: 62

----------------------------------------------------------------------

再次dig ChinaDNS，有结果了。。。。。
C:\Users\szx42>dig @192.168.1.1 -p 35353 interfacelift.com

; <<>> DiG 9.10.2-P4 <<>> @192.168.1.1 -p 35353 interfacelift.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7233
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;interfacelift.com.             IN      A

;; ANSWER SECTION:
interfacelift.com.      897     IN      A       206.190.152.82

;; Query time: 184 msec
;; SERVER: 192.168.1.1#35353(192.168.1.1)
;; WHEN: Thu Sep 03 17:03:32 ?D1ú±ê×?ê±?? 2015
;; MSG SIZE  rcvd: 52
----------------------------------------------------------------------

后续再向chinadns查询还是不正常，没有返回结果，具体多久就失效了我还没测试。。
其他不在那两个列表里面的域名都是这种情况，互不干扰。。。
root@OpenWrt:~# chinadns -v
Thu Sep  3 17:48:01 2015 CHNROUTE_FILE not specified, CHNRoute is disabled
Thu Sep  3 17:48:01 2015 chinadns.c:554 bind: Address already in use
Thu Sep  3 17:48:01 2015 Can't bind address 0.0.0.0:53
可以确定国内路由表没有问题，如图。
![image](https://cloud.githubusercontent.com/assets/4355746/9660219/1252d348-5287-11e5-96e4-7f5a18f1e85b.png)

root@OpenWrt:~# chinadns -c /etc/chinadns_chnroute.txt
Thu Sep  3 18:03:50 2015 chinadns.c:554 bind: Address already in use
Thu Sep  3 18:03:50 2015 Can't bind address 0.0.0.0:53

root@OpenWrt:~# chinadns -h
usage: chinadns [-h] [-l IPLIST_FILE] [-b BIND_ADDR] [-p BIND_PORT]
       [-c CHNROUTE_FILE] [-s DNS] [-m] [-v] [-V]
Forward DNS requests.

  -l IPLIST_FILE        path to ip blacklist file
  -c CHNROUTE_FILE      path to china route file
                        if not specified, CHNRoute will be turned
  -d                    off enable bi-directional CHNRoute filter
  -y                    delay time for suspects, default: 0.3
  -b BIND_ADDR          address that listens, default: 127.0.0.1
  -p BIND_PORT          port that listens, default: 53
  -s DNS                DNS servers to use, default:
                        114.114.114.114,208.67.222.222:443,8.8.8.8
  -m                    use DNS compression pointer mutation
                        (backlist and delaying would be disabled)
  -v                    verbose logging
  -h                    show this help message and exit
  -V                    print version and exit

Online help: <https://github.com/clowwindy/ChinaDNS>

root@OpenWrt:~# chinadns -m -c /etc/chinadns_chnroute.txt
Thu Sep  3 18:06:58 2015 chinadns.c:554 bind: Address already in use
Thu Sep  3 18:06:58 2015 Can't bind address 0.0.0.0:53

求助。。。。

**Comment by aa65535** [comment]
虽然你写了这么多内容，但是我依然没有得到任何有用的信息。
`accelerated-domains.china.conf` 和  `foreign_list.conf ` 是做什么用的？里面什么内容？好像 ChinaDNS 没有需要这个东西。
ChinaDNS 的设置？使用 `uci export chinadns` 打印一下。
`/etc/chinadns_chnroute.txt` 有没有经过修改？
使用 dig 测试时先用 ps 看一下 chinadns 的进程带有哪些参数？

**Comment by SuZixiong** [comment]
uci export chinadns输出，
config chinadns
	option chnroute '/etc/chinadns_chnroute.txt'
	option port '35353'
	option server '*.*.*.*:5050,223.5.5.5,223.6.6.6'
	option enable '1'
	option bidirectional '1'

accelerated-domains.china.conf 和 foreign_list.conf请查看这里，https://cokebar.info/archives/1410。
使用 dig 测试时先用 ps 看一下 chinadns 的进程带有哪些参数？这个是用什么命令？我是外行人。

**Comment by aa65535** [comment]
1.`accelerated-domains.china.conf` 作为 dnsmasq 的配置文件，如果是在这个文件中的域名无法解析，说明与 ChinaDNS 没有关系，检查一下这两个文件的格式是否正确。

2. 如果 `...:5050` 是自己搭建的DNS的话，检查一下是否支持压缩指针，另外不建议使用这类非标准端口作为 ChinaDNS 的服务器，因为数据并没有加密混淆，建议用法是搭配 ss-tunnel 或者shadowvpn。

3.如果自己对DNS配置不清楚，以及不清楚各级DNS查询是如何工作的情况下，建议使用最简答的配置方式。某些教程并不具有通用性。

**Comment by SuZixiong** [comment]
找到问题了，是自己建的DNS服务器不支持压缩支持，参看https://github.com/aa65535/openwrt-dist-luci/issues/11 这个问题就解决了。
谢谢各位。
