### ISSUE TITLE
can you build a bin for "mvebu"

### ISSUE THREAD

**Issue by ohyeah521** [aa65535/openwrt-chinadns#25]
i had a router "linksys wrt1900ac" , so i need this bin. thank you.

**Comment by houzi-** [comment]
@ohyeah521 
Please see here:
http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/packages/shadowsocks-libev_2.2.3-1_mvebu.ipk

**Comment by ohyeah521** [comment]
@houzi-  thank you.

**Comment by immartian** [comment]
is that ChinaDNS or just shadowsocks?
