### ISSUE TITLE
openwrt15.05问题

### ISSUE THREAD

**Issue by xingezhang** [aa65535/openwrt-chinadns#26]
首先表示感谢，用了很久了
昨天全新刷机到openwrt15.05正式版，安装ChinaDNS_1.3.2_ar71xx.ipk和luci-app-chinadns_1.3.4-1_all.ipk
openwrt的配置界面怎么都找不到chindns，最后翻了很多帖子，才发现要在/etc/config/下面建立chinadns文件，内容来自源码包里的chinadns.config，我记得之前14.07安装1.3.0时好像没有这个问题，请检查一下，谢谢！

**Comment by aa65535** [comment]
需要安装 https://sourceforge.net/projects/openwrt-dist/files/chinadns/ 里的版本。
