### ISSUE TITLE
上游DNS设置问题

### ISSUE THREAD

**Issue by wangxj-nemo** [aa65535/openwrt-chinadns#28]
1, 上级路由器A的WLAN的DNS 是202，LAN范围192.168.1.1

2，下级路由器B的WLAN的DNS192.168.1.1, LAN范围192.168.2.1

3，chinadns安装在B上，设置其上游DNS为192.168.1.1和自己的DNS服务器，chinadns不能启动。

是设置问题，还是软件问题（192.168.1.1不被识别是墙内有效DNS）?

**Comment by aa65535** [comment]
在命令行启动，可以查看错误信息。

**Comment by wangxj-nemo** [comment]
错误信息曾经查看过，大意是至少需要一个墙内DNS 一个墙外DNS,显然192.168.1.1没有被判别为墙外DNS,按理B的dns查询会提交给A的202，也应该可行。应该是没有考虑局域网里面路由器级联这种问题。

**Comment by aa65535** [comment]
@wangxj-nemo  不在 chnroute 里的 IP 都会被认为是国外 IP，确认一下是不是修改过 chnroute。

**Comment by wangxj-nemo** [comment]
哦，这样啊，晚上回家看看是不是跟chnroute有关。

**Comment by wangxj-nemo** [comment]
192.168.1.1并不在chnroute里面。
