### ISSUE TITLE
chinadns运行一段时间出错了，日志如下

### ISSUE THREAD

**Issue by ohyeah521** [aa65535/openwrt-chinadns#30]
系统环境介绍： openwrt15.05
软件环境：ss开启dns解析，配合chinadns。默认chinadns接管路由器的dns服务

运行一段时间后，所有国外网站打不开：Chroem提示 无法显示网页，ERR_NAME_NOT_RESOLVED

以github为例，日志如下：

Mon Nov  9 15:17:39 2015 request github.com
Mon Nov  9 15:17:39 2015 response github.com from 114.114.114.114:53 - 192.30.252.130, filter
Mon Nov  9 15:17:41 2015 request github.com
Mon Nov  9 15:17:42 2015 response github.com from 114.114.114.114:53 - 192.30.252.130, filter
Mon Nov  9 15:17:42 2015 request github.com
Mon Nov  9 15:17:43 2015 response github.com from 114.114.114.114:53 - 192.30.252.130, filter
Mon Nov  9 15:17:43 2015 request github.com
Mon Nov  9 15:17:44 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:45 2015 request github.com
Mon Nov  9 15:17:45 2015 request github.com
Mon Nov  9 15:17:46 2015 response github.com from 114.114.114.114:53 - 192.30.252.131, filter
Mon Nov  9 15:17:46 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:47 2015 request github.com
Mon Nov  9 15:17:48 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:48 2015 request github.com
Mon Nov  9 15:17:49 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:49 2015 request github.com
Mon Nov  9 15:17:49 2015 request github.com
Mon Nov  9 15:17:49 2015 request github.com
Mon Nov  9 15:17:50 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:50 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:50 2015 response github.com from 114.114.114.114:53 - 192.30.252.131, filter
Mon Nov  9 15:17:51 2015 request github.com
Mon Nov  9 15:17:51 2015 request github.com
Mon Nov  9 15:17:52 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:52 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:55 2015 request github.com
Mon Nov  9 15:17:55 2015 request github.com
Mon Nov  9 15:17:56 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:17:56 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:01 2015 request github.com
Mon Nov  9 15:18:01 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:02 2015 request github.com
Mon Nov  9 15:18:02 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:03 2015 request github.com
Mon Nov  9 15:18:03 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:05 2015 request github.com
Mon Nov  9 15:18:05 2015 request github.com
Mon Nov  9 15:18:05 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:05 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:06 2015 request github.com
Mon Nov  9 15:18:06 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:07 2015 request github.com
Mon Nov  9 15:18:07 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:08 2015 request github.com
Mon Nov  9 15:18:08 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:09 2015 request github.com
Mon Nov  9 15:18:09 2015 request github.com
Mon Nov  9 15:18:09 2015 request github.com
Mon Nov  9 15:18:09 2015 response github.com from 114.114.114.114:53 - 192.30.252.130, filter
Mon Nov  9 15:18:09 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:09 2015 response github.com from 114.114.114.114:53 - 192.30.252.129, filter
Mon Nov  9 15:18:11 2015 request github.com
Mon Nov  9 15:18:11 2015 request github.com
Mon Nov  9 15:18:11 2015 response github.com from 114.114.114.114:53 - 192.30.252.129, filter
Mon Nov  9 15:18:11 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:15 2015 request github.com
Mon Nov  9 15:18:15 2015 request github.com
Mon Nov  9 15:18:15 2015 response github.com from 114.114.114.114:53 - 192.30.252.128, filter
Mon Nov  9 15:18:15 2015 response github.com from 114.114.114.114:53 - 192.30.252.131, filter

希望能尽快解决。

**Comment by aa65535** [comment]
国外DNS没有结果返回

**Comment by ohyeah521** [comment]
@aa65535 是国外的没有返回结果，还是说没法发送给国外？我没有看到类似这样的日志：
meta.stackoverflow.com from 127.0.0.1:1053 - 198.252.206.16, pass

是只有接收到了才打印这样的日志吗?能不能添加一个参数，查看chinadns发送的请求，是发送了请求没有响应，还是没发送。
