### ISSUE TITLE
为什么有时候国外的IP都会向国内的dns服务器解析？

### ISSUE THREAD

**Issue by pexcn** [aa65535/openwrt-chinadns#32]
![err](https://cloud.githubusercontent.com/assets/4590439/11150100/1855ed7c-8a61-11e5-9b74-2d7c360e0253.png)

**Comment by pexcn** [comment]
都被过滤了。。

**Comment by pexcn** [comment]
一个国内的DNS服务器，一个国外VPS的自建的DNS服务器，25端口

**Comment by aa65535** [comment]
已确认，的确有这个问题。

**Comment by ohyeah521** [comment]
这个问题好久了，终于被确认了。

**Comment by pexcn** [comment]
vps用pdnsd搭建dns服务器效果好像会好些，之前用dnsmasq的一直有这样的问题。。

**Comment by flipphos** [comment]
我用的就是自己vps上的pdnsd，自定义的查询端口，op上也装了pdnsd作为chinadns后端，没有明显碰到你们说的这个问题。

Best Regards,
Hong
