### ISSUE TITLE
chindns配合pdnsd的问题

### ISSUE THREAD

**Issue by diaochaju** [aa65535/openwrt-chinadns#33]
发现pdnsd配合chinadns用udp方式查询dns的速度很快，请问用udp方式查询好国外非53端口的dns服务器会被污染dns吗？(服务器是用pdnsd搭建的)

**Comment by mysteriouss** [comment]
query_method=tcp_only; 查询国外的DNS 可以保证无污染；
在ss速度还可以情况下，可以直接使用ss server的UDP Forward（ss-tunnel好像只支持dig +tcp的）；
采用dnsmasq -> pdnsd -> redsocks sock5 -> shadowsocks-libev（不是spec），这样应该就可以替掉ChinaDNS了；

以下pdnsd.conf仅供参考

global {
	perm_cache=102400;
	cache_dir="/var/pdnsd";
#	pid_file = /var/run/pdnsd.pid;
	run_as="nobody";
	server_ip = 0.0.0.0;  # Use eth0 here if you want to allow other
				# machines on your network to query pdnsd.
	server_port = 5555;
	status_ctl = on;
	paranoid=on;       # This option reduces the chance of cache poisoning
	                   # but may make pdnsd less efficient, unfortunately.
	query_method=tcp_only;
	min_ttl=15m;       # Retain cached entries at least 15 minutes.
	max_ttl=1w;        # One week.
	timeout=10;        # Global timeout option (10 seconds).
	neg_domain_pol=on;
	udpbufsize=10240;   # Upper limit on the size of UDP messages.
}

server{
 label = "114";
 ip = 114.114.114.114,1.2.4.8;
 proxy_only = on;
 policy = included;
 exclude = .gmail.com,
 .google-analytics.com,
 .google.cn,
 .google.com,
 .facebook.com,
 .instagram.com,
 .youtube.com,
 .cdninstagram.com,
 .google.com.hk,
 .google.co.jp;
}

# The following section is most appropriate if you have a fixed connection to
# the Internet and an ISP which provides good DNS servers.
server {
	label= "dns";
	ip = 127.0.0.1;  # Put your ISP's DNS-server address(es) here.
	port = 5000; //Shadowsocks UDP Forward (ss-tunnel)
	proxy_only=on;     # Do not query any name servers beside your ISP's.
	                   # This may be necessary if you are behind some
	                   # kind of firewall and cannot receive replies
	                   # from outside name servers.
	timeout=3;         # Server timeout; this may be much shorter
			   # that the global timeout option.
	uptest=if;         # Test if the network interface is active.
	interface=eth0;    # The name of the interface to check.
	interval=10m;      # Check every 10 minutes.
	purge_cache=off;   # Keep stale cache entries in case the ISP's
			   # DNS servers go offline.
	edns_query=no;    # Use EDNS for outgoing queries to allow UDP messages
			   # larger than 512 bytes. May cause trouble with some
			   # legacy systems.
	exclude=.baidu.com,.weibo.com,.taobao.com,.jd.com;
}

**Comment by flipphos** [comment]
我是利用chinadns的区分国内外ip的分流功能，便于国内cdn生效。
国外ip就级连本地op的pdnsd，然后通过vps上的二级pdnsd的非标准udp端口进行解析。到目前没有发生过污染。（用了半年多）速度也有保障。
测试过，如果是香港的vps，dig耗时在50ms上下，很少有超过100ms的。米国的vps也就200-300ms。
上网滞后感不明显。
DNS解析流程：
dnsmasq-chinadns- pdnsd（op）-pdnsd（vps）-国外DNS。





Best Regards,
Hong

**Comment by aa65535** [comment]
目前非 53 端口还没被污染

**Comment by q158073378252010** [comment]
非53 端口早已污染只是地区特例
