### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ohyeah521** [aa65535/openwrt-chinadns#34]
目前采用chinadns + shadowsocks 开启UDP进行dns解析的模式来处理dns污染。

目前存在的问题：
有时候一个国外的域名，同时采用114.114.114.114 和本机的127.0.0.1:1080 （这里最终走ss）进行dns查询。有时候ss的没有返回，而114.114.114.114 返回了真实的IP地址。这时候浏览器就不能打开网页了，因为国内的dns应答被过滤掉了，而国外的dns没有应答，这样就出错了。

我的想法是： 对于国外的域名或IP地址，如果国内的有应答了，就把它存起来，等带国外的结果，如果超过0.3秒还没有应答，就已国内的dns应答为结果返回。这样就可以解救有些时候不能上网的问题，然后过一段时间又可以了。

**Comment by aa65535** [comment]
如果这样的话就无法防止DNS投毒了

**Comment by ohyeah521** [comment]
@aa65535  可以啊，就是做一个判断而已，如果我们自己的国外的dns服务器有应答，那就优先采用国外的dns服务器，如果我们自己的国外的dns服务器没有应答，那就采用国内的，这样的话既能防毒，也能解救国外dns服务器超时没有响应的问题。
