### ISSUE TITLE
添加了/etc/opkg.conf 依然无法安装

### ISSUE THREAD

**Issue by thank243** [aa65535/openwrt-chinadns#35]
硬件信息：OpenWrt Chaos Calmer 15.05 / LuCI 15.05-19-g488c5a7 Release (git-15.258.28302-30f6fe8)

按首页安装说明添加了src/gz openwrt_dist http://openwrt-dist.sourceforge.net/releases/ar71xx/packages
src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/releases/luci/packages

之后执行

opkg update

提示 

Downloading http://openwrt-dist.sourceforge.net/releases/ar71xx/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/openwrt_dist.
Downloading http://openwrt-dist.sourceforge.net/releases/ar71xx/packages/Packages.sig.
wget: server returned error: HTTP/1.1 404 Not Found
Signature check failed.
Remove wrong Signature file.
Downloading http://openwrt-dist.sourceforge.net/releases/luci/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/openwrt_dist_luci.
Downloading http://openwrt-dist.sourceforge.net/releases/luci/packages/Packages.sig.
wget: server returned error: HTTP/1.1 404 Not Found
Signature check failed.
Remove wrong Signature file.

继续执行opkg install ChinaDNS

提示

root@GL-AR150:~# opkg install ChinaDNS
Unknown package 'ChinaDNS'.
Collected errors:
 * opkg_install_cmd: Cannot install package ChinaDNS.
root@GL-AR150:~#

**Comment by aa65535** [comment]
删除或者注释掉 /etc/opkg.conf 中的 `option check_signature 1`
