### ISSUE TITLE
如何自建一台可信DNS？

### ISSUE THREAD

**Issue by xcjiang** [aa65535/openwrt-chinadns#37]
最近加入的可信dns这个feature还是挺有意思的，但怎么能拥有一台可信DNS呢？ 如果DNS放在国外，肯定会被污染，如果通过ss-tunnel连接，那不是又回到老路了吗？ 如果DNS放在国内，那如何能做到可信？  不知道有什么手段能建立一台可信DNS。

**Comment by xcjiang** [comment]
用dnscrypt成功自建一台可信DNS，配合chinadns效果非常好，比用ss-tunnel中转强多了。

**Comment by ohyeah521** [comment]
@xcjiang  能给个部署dnscrypt的详细教程吗？
