### ISSUE TITLE
Could I use Shadowvpn as the upstream dns server?

### ISSUE THREAD

**Issue by lixingcong** [aa65535/openwrt-chinadns#38]
Would the dns query result be polluted when I set 10.7.0.1:53 as the upstream sever of ChinaDNS?

Now my Shadowvpn works well. Its gateway is 10.7.0.1.
And I have installed pdnsd on my host listening port 53.
I wonder if that all the traffic walks through tun0(10.7.0.1) is encrypted?
My idea is that let dns request walk through Shadowvpn to prevent GFW dns pollution.

![capture](https://cloud.githubusercontent.com/assets/7625115/11496886/1b3dbe6e-9850-11e5-9b8e-9a4cac4ec0e4.PNG)

**Comment by hdstar2009** [comment]
yes,you can. and you can let pdnsd to use a tcp port not default53 such as 9999.Then you can setup the chinadsn upstream dns like this:114.114.114.114,10.7.0.1:9999

**Comment by lixingcong** [comment]
@hdstar2009 
Thanks for your reply. After taking a packet capture on my router, I found all the DNS packets were encrypted.

    opkg update
    opkg install tcpdump
    tcpdump -i any -w /tmp/all.cap
    
I analysed the file 'all.cap' with Wireshark. It shows that it is a good way to prevent your DNS request and answer packets from being polluted.

**Comment by aa65535** [comment]
ShadowVPN support UDP protocol.
