### ISSUE TITLE
怎么够使用国内纯净DNS

### ISSUE THREAD

**Issue by heiybb** [aa65535/openwrt-chinadns#40]
在上游服务器选项中，第二个服务器想使用自建的在国内的纯净DNS，但是提示必须使用国外的IP，应该怎么设置？

**Comment by hdstar2009** [comment]
用最新版本

**Comment by cokebar** [comment]
在chnroute.list中将你国内DNS服务器的IP地址排除即可

**Comment by 523860169** [comment]
@cokebar 是新建一个/etc/chnroute.list文件还是在/etc/chinadns_chnroute.txt中操作？

**Comment by cokebar** [comment]
@523860169 指的是你chinadns配置中国内路由表填入的文件，当前版本下默认是/etc/chinadns_chnroute.txt

**Comment by 523860169** [comment]
@aa65535 可信dns？不是很明白。我现在是填了两个dns，第一个是isp的，第二个就是中科大的dns，地址都是国内ip，没有关系吧？其实opendns的也可以，但是opendns间歇性超时，所以不是很稳定

**Comment by aa65535** [comment]
@523860169 https://github.com/aa65535/openwrt-chinadns/releases/tag/v1.3.2-2

**Comment by 523860169** [comment]
@aa65535 这是我的配置，可还是有问题，具体看https://github.com/aa65535/openwrt-chinadns/issues/65

config chinadns
	option enable '1'
	option bidirectional '0'
	option chnroute '/etc/chinadns_chnroute.txt'
	option port '5353'
	option server '211.138.151.161,202.141.176.93#5353'
