### ISSUE TITLE
Openwrt配置ChinaDNS疑问

### ISSUE THREAD

**Issue by kuoruan** [aa65535/openwrt-chinadns#41]
在配置Openwrt使用ChinaDNS时，有两种方式：
1.本地服务器 填写 127.0.0.1#5353
2.DNS转发 填写 127.0.0.1#5353

请问这两种方式有什么区别？用哪种比较好？

**Comment by aa65535** [comment]
没区别.

**Comment by kuoruan** [comment]
日了狗了，ChinaDNS启动了，也设置好了DNS服务器，但是dig发现走的还是本地的53端口而不走5353，请问这个怎么解决？

**Comment by flipphos** [comment]
dnsmasq里面设置dns走本地5353了吗？

**Comment by kuoruan** [comment]
就是全部都设置好了，才不知道怎么弄了

**Comment by flipphos** [comment]
dig 时用的-p 5353指定端口了吗？

**Comment by kuoruan** [comment]
dig时强制使用 -p 5353时是可以解析到正确的结果的，但是不加参数直接dig就不行

**Comment by flipphos** [comment]
dig -p 5353 能走正确就行啦。
建议你把ipip.net加入黑名单强制走你自己的dns和ss。然后对比访问ip138.com(国内ip)的结果，就能快速区分是否ss和dns都成功了。

**Comment by kuoruan** [comment]
我shadowsocks的客户端是在电脑上的，我只需要路由器dns防污染就行了，怎样才能确定路由器解析的时候走的ChinaDNS呢？

**Comment by flipphos** [comment]
能访问被强网站就说明正常。假设你chinadns工作不正常，就谈不上正常科学上网了。

**Comment by kuoruan** [comment]
我不开ChinaDNS也能访问。。现在我主要的问题不是墙的问题，墙怎么都能翻，主要是想解决dns污染的问题

**Comment by flipphos** [comment]
dig  -p port wsj.com（或者其他被强网站）得到正确ip，说明你的dns服务介入工作正常。

**Comment by kuoruan** [comment]
我将ChinaDNS的源码全部清除，重新下载了最新的源码，重新编译后，现在正常了，感谢！
依照https://velaciela.ms/openwrt-shadowsocks-chinadns这篇文章所说，需要将“忽略解析文件”同时勾上么？

**Comment by aa65535** [comment]
`忽略解析文件` 必须勾上

**Comment by kuoruan** [comment]
只勾了个 “忽略解析文件” 没勾 “忽略 /etc/hosts” 也能正常使用了，感谢！
