### ISSUE TITLE
国内小运营商网络访问cdn节点

### ISSUE THREAD

**Issue by sanjusss** [aa65535/openwrt-chinadns#42]
本人最近使用北京网邻宽带——一家覆盖面积只有几平方公里的宽带运营商的网络——使用chinadns时不时ps4走国外的cdn节点。
然后不经意间，我发现了：
PING www.a.shifen.com (220.181.111.188): 56 data bytes
64 bytes from 220.181.111.188: icmp_seq=0 ttl=52 time=10.245 ms
64 bytes from 220.181.111.188: icmp_seq=1 ttl=52 time=16.607 ms
64 bytes from 220.181.111.188: icmp_seq=2 ttl=52 time=24.203 ms
64 bytes from 220.181.111.188: icmp_seq=3 ttl=52 time=6.583 ms
64 bytes from 220.181.111.188: icmp_seq=4 ttl=52 time=7.546 ms
64 bytes from 220.181.111.188: icmp_seq=5 ttl=52 time=11.021 ms
64 bytes from 220.181.111.188: icmp_seq=6 ttl=52 time=21.882 ms
64 bytes from 220.181.111.188: icmp_seq=7 ttl=52 time=8.396 ms
64 bytes from 220.181.111.188: icmp_seq=8 ttl=52 time=7.035 ms
64 bytes from 220.181.111.188: icmp_seq=9 ttl=52 time=7.112 ms
64 bytes from 220.181.111.188: icmp_seq=10 ttl=52 time=12.095 ms
64 bytes from 220.181.111.188: icmp_seq=11 ttl=52 time=8.043 ms
64 bytes from 220.181.111.188: icmp_seq=12 ttl=52 time=147.277 ms
64 bytes from 220.181.111.188: icmp_seq=13 ttl=52 time=7.625 ms
64 bytes from 220.181.111.188: icmp_seq=14 ttl=52 time=6.483 ms
64 bytes from 220.181.111.188: icmp_seq=15 ttl=52 time=8.829 ms
64 bytes from 220.181.111.188: icmp_seq=16 ttl=52 time=6.981 ms
64 bytes from 220.181.111.188: icmp_seq=17 ttl=52 time=8.043 ms
64 bytes from 220.181.111.188: icmp_seq=18 ttl=52 time=7.470 ms
64 bytes from 220.181.111.188: icmp_seq=19 ttl=52 time=6.447 ms
64 bytes from 220.181.111.188: icmp_seq=20 ttl=52 time=9.046 ms
64 bytes from 220.181.111.188: icmp_seq=21 ttl=52 time=6.596 ms
64 bytes from 220.181.111.188: icmp_seq=22 ttl=52 time=8.473 ms
64 bytes from 220.181.111.188: icmp_seq=23 ttl=52 time=7.468 ms
64 bytes from 220.181.111.188: icmp_seq=24 ttl=52 time=109.848 ms

没错，这小运营商的网络极不稳定，连baidu.com的延迟变化幅度极大。也就是说查询cdn节点时，国内dns返回时间可能比国外要长，然后chinadns直接使用了先返回的国外节点。
目前，我用下面的dns：
219.141.140.10,219.141.136.10,202.106.196.115,202.106.0.20,127.0.0.1:5300
四个北京dns（网通+电信） vs 一个国外dns（谷歌）
然而依旧有可能走国外节点（有几成概率吧）：
PING sonycoment.vo.llnwd.net (203.77.188.253): 56 data bytes
64 bytes from 203.77.188.253: icmp_seq=0 ttl=43 time=189.938 ms
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
64 bytes from 203.77.188.253: icmp_seq=4 ttl=43 time=188.064 ms
^C
--- sonycoment.vo.llnwd.net ping statistics ---
5 packets transmitted, 2 packets received, 60.0% packet loss

真是日了狗了。

nslookup gs2.ww.prod.dl.playstation.net
;; Truncated, retrying in TCP mode.
Server:		192.168.1.1
Address:	192.168.1.1#53

** server can't find gs2.ww.prod.dl.playstation.net: NXDOMAIN

**Comment by suikatomoki** [comment]
https://cokebar.info/archives/1410
