### ISSUE TITLE
编译时缺少依赖库

### ISSUE THREAD

**Issue by sanjusss** [aa65535/openwrt-chinadns#44]
Package ChinaDNS is missing dependencies for the following libraries:
libc.so
libgcc_s.so.1

版本为1月10日trunk版

**Comment by aa65535** [comment]
编译环境本身需要一下依赖包的, 需要自己额外安装, 请参考 Openwrt 的 Wiki 安装.

**Comment by sanjusss** [comment]
我想问下解决方法，menuconfig中我已经选了libc和libgcc，编译chinadns的时候却说我没有。而且前几天我也编译过，是成功的，今天我把openwrt版本svn up后，就不行了。

**Comment by aa65535** [comment]
是「编译环境」需要依赖, 不止是 openwrt 里.

**Comment by sanjusss** [comment]
![qq 20160110221401](https://cloud.githubusercontent.com/assets/8220722/12221954/b2a6b48e-b7e7-11e5-9311-2a4a24dc05f7.png)
你看，无论是在openwrt中还是在本机中，都有libgcc_s.so.1，然而编译时就提示没有。
我如果没有libgcc_s.so.1，就连openwrt本体都都无法编译

**Comment by ideal** [comment]
试了下，其实执行下`scripts/feeds update -a`就可以了，或者更少一点，`scripts/feeds update packages`
