### ISSUE TITLE
运行一段时间后失效，查看日志只有request没有response

### ISSUE THREAD

**Issue by RemiDre** [aa65535/openwrt-chinadns#45]
——————————————————————————————————
2016.01.13
——————————————————————————————————
今天发现的问题是，国外dns解析服务器无反应，只有国内的有反应。
怀疑是被GFW过滤掉了？
211.137.191.26是本地isp的dns
日志：
Wed Jan 13 08:11:11 2016 request live.github.com from 211.137.191.26:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Wed Jan 13 08:11:11 2016 response live.github.com from 211.137.191.26:53 - 192.30.252.91, filter
Wed Jan 13 08:11:11 2016 response live.github.com from 211.137.191.26:53 - 192.30.252.91, filter
Wed Jan 13 08:11:15 2016 request live.github.com from 211.137.191.26:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Wed Jan 13 08:11:15 2016 response live.github.com from 211.137.191.26:53 - 192.30.252.91, filter
Wed Jan 13 08:11:15 2016 response live.github.com from 211.137.191.26:53 - 192.30.252.89, filter

dig 8.8.8.8 也毫无反应
DIG：
root@OpenWrt:~# dig @8.8.8.8 www.baidu.com

; <<>> DiG 9.9.4 <<>> @8.8.8.8 www.baidu.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

国内dns解析有反应
root@OpenWrt:~# dig @211.137.191.26 www.baidu.com

; <<>> DiG 9.9.4 <<>> @211.137.191.26 www.baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24458
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 5, ADDITIONAL: 6

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.baidu.com.                 IN      A

;; ANSWER SECTION:
www.baidu.com.          281     IN      CNAME   www.a.shifen.com.
www.a.shifen.com.       247     IN      A       111.13.100.92
www.a.shifen.com.       247     IN      A       111.13.100.91

;; AUTHORITY SECTION:
a.shifen.com.           87      IN      NS      ns5.a.shifen.com.
a.shifen.com.           87      IN      NS      ns4.a.shifen.com.
a.shifen.com.           87      IN      NS      ns3.a.shifen.com.
a.shifen.com.           87      IN      NS      ns1.a.shifen.com.
a.shifen.com.           87      IN      NS      ns2.a.shifen.com.

;; ADDITIONAL SECTION:
ns1.a.shifen.com.       175     IN      A       61.135.165.224
ns2.a.shifen.com.       175     IN      A       180.149.133.241
ns3.a.shifen.com.       175     IN      A       61.135.162.215
ns4.a.shifen.com.       175     IN      A       115.239.210.176
ns5.a.shifen.com.       175     IN      A       119.75.222.17

;; Query time: 14 msec
;; SERVER: 211.137.191.26#53(211.137.191.26)
;; WHEN: Wed Jan 13 08:19:55 GMT 2016
;; MSG SIZE  rcvd: 271

——————————————————————————————————
2016.01.12
——————————————————————————————————
Tue Jan 12 10:20:39 2016 request www.baidu.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:39 2016 request www.baidu.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:40 2016 request www.baidu.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:42 2016 request www.baidu.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:43 2016 request nexus.officeapps.live.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:43 2016 request nexus.officeapps.live.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:44 2016 request nexus.officeapps.live.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:44 2016 request imap.qq.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:44 2016 request docker-test.leancloud.cn from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:44 2016 request rtm53.leancloud.cn from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:46 2016 request nexus.officeapps.live.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:46 2016 request rm.api.weibo.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:46 2016 request rm.api.weibo.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:46 2016 request www.google.co.jp from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:46 2016 request www.google.co.jp from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
Tue Jan 12 10:20:46 2016 request www.baidu.com from 114.114.114.114:53 8.8.8.8:53 208.67.222.222:443 127.0.0.1:5151
如上日志，只有request没有response，重启路由器才能解决
其中127.0.0.1:5151 是我的ss
配置没有问题，因为之前稳定用了差不多1个月。

**Comment by RemiDre** [comment]
其中127.0.0.1:5151 是我的ss

**Comment by edison0354** [comment]
同……
国内服务器用ISP的和114的都试过了
国外服务器是用着ss转发出来的8.8.4.4，opendns的443端口也试过，我现在删掉了opedns，只有ISP的和ss转发的在测试
Google的域名，直接dig ss转发出来那个端口是没问题的，然后dig chinadns的端口就不行了……所以肯定不是上游服务器的问题
于是实际上国外网站都无法解析，只有国内网站正常访问
之前也是没问题，也是最近开始的，具体表现为运行一段时间之后开始出问题，然后放置Play一会人就又好了，然后如此循环……

**Comment by gonejack** [comment]
同楼上，我没有使用ss-tunnel转发，填的是一个香港的DNS服务器，也照样会隔段时间就无法解析，放置一会儿又好了。

**Comment by lixingcong** [comment]
我已经放弃chinadns换dnsmasq-full了

**Comment by bazingaterry** [comment]
我也遇到上面的情况，用的是最新版，自己编译的。

**Comment by aa65535** [comment]
试试搭配 https://github.com/aa65535/openwrt-dns-forwarder

**Comment by cherrot** [comment]
为什么转成TCP就能解决?
