### ISSUE TITLE
请问我安装了chinadns和luci-app-chinadns后，luci里没有chinadns的选项是为什么？

### ISSUE THREAD

**Issue by Syh15198462** [aa65535/openwrt-chinadns#46]
路由是网件4300 v1
固件版本：OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45)
内核版本：3.18.20
ChinaDNS版本是ChinaDNS_1.3.2-3_ar71xx
luci-app-ChinaDNS版本是luci-app-chinadns_1.3.4-1_all

**Comment by Syh15198462** [comment]
问题已解决 ChinaDNS_1.3.2-3_ar71xx.ipk的内容是luci-app-chinadns。
![image](https://cloud.githubusercontent.com/assets/15834651/12516194/2a4b9486-c167-11e5-9ec3-1f7b4dc288f3.png)
![image](https://cloud.githubusercontent.com/assets/15834651/12516217/491d53d6-c167-11e5-8e07-45be415a1d29.png)

**Comment by aa65535** [comment]
这个应该是运营商缓存导致的, 两者包大小有相差10倍.
