### ISSUE TITLE
ar71xx平台下安装有遇到错误信息

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-chinadns#47]
Collected errors:
 * pkg_run_script: package "shadowsocks-libev-spec" postinst script returned status 127.
 * opkg_configure: shadowsocks-libev-spec.postinst returned 127.
 * pkg_run_script: package "ChinaDNS" postinst script returned status 127.
 * opkg_configure: ChinaDNS.postinst returned 127.
 * pkg_run_script: package "ShadowVPN" postinst script returned status 127.
 * opkg_configure: ShadowVPN.postinst returned 127.

不知道具体是什么。贴出来反馈下。

**Comment by lixingcong** [comment]
换op 15.05版

**Comment by hdstar2009** [comment]
用15.05的op，就会提示内核版本不是3.18，虽然可以强行安装，但是不知道会不会有其他问题。
另外op官方似乎没有见到有官方的ar71xx的15.05版固件。
