### ISSUE TITLE
可信DNS比国内DNS先返回结果

### ISSUE THREAD

**Issue by xcjiang** [aa65535/openwrt-chinadns#48]
如果可信DNS比国内DNS先返回结果，则会采用可信DNS的返回结果而不是国内DNS的返回结果，会造成国内网站被解析到了海外CDN的地址，此问题如何解决？

**Comment by aa65535** [comment]
这是软件的预期结果。
不要在可信DNS上面使用缓存，应该在ChinaDNS下游使用缓存。

**Comment by xcjiang** [comment]
并没有使用缓存，在我这里访问香港的dns快过114.
软件的预期结果应该是解决cdn的问题，这正是chinadns设计的目的。我看了代码，代码里有delay的设计，但在有可信dns的时候是不用的，我觉得把它用起来应该就可以解决问题？

**Comment by bazingaterry** [comment]
@xcjiang ChinaDNS 有双向过滤的选项。

**Comment by xcjiang** [comment]
@bazingaterry 我想你可以误解了双向过滤的含义，双向过滤跟我说的没有关系。

**Comment by aa65535** [comment]
软件设计的是首先要保证提供的解析结果是可靠的，其次才是线路优化。

**Comment by xcjiang** [comment]
@aa65535 现有代码不是有delay的实现吗？ 至少在我看来只要能用来了应该就可以解决问题。
