### ISSUE TITLE
双向过滤可能存在bug

### ISSUE THREAD

**Issue by sanjusss** [aa65535/openwrt-chinadns#50]
国内返回的部分结果也被过滤了。
版本为1.3.2-3
启动参数：
`/usr/bin/chinadns -p 5353 -s 218.2.135.1,127.0.0.1:5300 -c /etc/chinadns_chnroute.txt -d -m`

日志
```
Sat Apr 16 10:17:18 2016 request news.sina.com.cn from 218.2.135.1:53 127.0.0.1:5300
Sat Apr 16 10:17:18 2016 response news.sina.com.cn from 218.2.135.1:53 - pass
Sat Apr 16 10:17:18 2016 response news.sina.com.cn from 127.0.0.1:5300 - pass
```
在/etc/chinadns_chnroute.txt的末尾，我强行指定dns服务器和新浪南京服务器为国内（原本这两个ip也在路由表中）：

![qq 20160416104451](https://cloud.githubusercontent.com/assets/8220722/14578660/46490dda-03c0-11e6-849d-eb2b0b2cd739.png)

在PC上使用路由器dns服务器查询超时：
![qq 20160416104545](https://cloud.githubusercontent.com/assets/8220722/14578666/6087afd0-03c0-11e6-85b3-f94256921ec9.png)

其他设置：
![qq 20160416104957](https://cloud.githubusercontent.com/assets/8220722/14578680/01c3c19a-03c1-11e6-86fd-a5b8d6546f2b.png)
![qq 20160416105005](https://cloud.githubusercontent.com/assets/8220722/14578679/01bf7d56-03c1-11e6-894a-195b6af2143d.png)

**Comment by sanjusss** [comment]
补充：版本为1.3.2-3

**Comment by aa65535** [comment]
你添加的两条，在chnroute里有覆盖 `202.102.0.0/19` `218.2.0.0/15`。
双向过滤只是丢掉国外DNS服务器返回的国内解析结果而已，这个功能并不常用。

**Comment by sanjusss** [comment]
我知道我错在哪儿了。我是从http://ipblock.chacuo.net/down/t_file=c_CN下载的ip段。
这个网站提供的ip范围没有错，但子网掩码和分段是错的。

唉，这个网站的ip范围直接处理起来太麻烦，我还是用apnic的吧
