### ISSUE TITLE
停用chinadns之后，网址无法解析

### ISSUE THREAD

**Issue by arfaWong** [aa65535/openwrt-chinadns#51]
停用chinadns
LuCI 中定位至「网络 - DHCP/DNS」
「基本设置」 本地服务器 留空
「HOSTS和解析文件」取消勾选 忽略解析文件
重启路由，网址无法解析

**Comment by lixingcong** [comment]
取消勾选 忽略解析文件下面填入
/tmp/resolv.conf.auto
