### ISSUE TITLE
Still being poisoned

### ISSUE THREAD

**Issue by droseacc** [aa65535/openwrt-chinadns#52]
I've set up OpenWrt+shadowsocks-libev+ChinaDNS on my router and it works great.  Trying on a friends now, has a 4mb flash so I used the polarssl builds. 

I've managed to get shadowsocks-libev-polarssl working and have installed ChinaDNS but can only visit google/gmail, no other blocked sites.  I'm new to OpenWrt so I've probably missed something but I've been trying for hours, any ideas?

**Comment by w18g** [comment]
install bind-dig and dig around.

1) Your default dns
dig youtube.com

2) Use a PRC DNS
dig @114.114.114.114 youtube.com

3) Use a Google DNS or better yet some other DNS
dig @8.8.4.4 youtube.com

Compare results....

note: something wrong with 8.8.8.8. and 8.8.4.4 these days....

**Comment by droseacc** [comment]
I solved the issue, but now I have another. ChinaDNS seems to be periodically failing and only letting Chinese websites through, and ALL foreign traffic fails, as if it's only letting traffic on the ignore/CHNroute list through, any ideas on this?
