### ISSUE TITLE
有添加tcp查询的计划吗

### ISSUE THREAD

**Issue by suikatomoki** [aa65535/openwrt-chinadns#54]
为了同时应对运营商的dns劫持和udp丢包。目前国内114dns和119dns均支持tcp查询，可以应对劫持，udp丢包也可以走tcp解决。
或者，如果不方便为chinadns添加tcp查询功能，有啥其他方法同时解决以上两个问题吗？

**Comment by bazingaterry** [comment]
@suikatomoki 本地可以用 pdnsd 中转一下

**Comment by suikatomoki** [comment]
@bazingaterry 方便给出pdnsd和chinadns的配置吗？

**Comment by bazingaterry** [comment]
`pdnsd.conf`

```
global {
    perm_cache=4096;
    cache_dir="/usr/local/var/cache/pdnsd";
    server_ip=0.0.0.0;
    server_port=5050;
    status_ctl=on;
    paranoid=on;
    query_method=tcp_only;
    min_ttl=24h;
    max_ttl=1w;
    timeout=5;
    neg_domain_pol=on;
    udpbufsize=1024;
}
server {
    label= "US";
    ip=1.2.3.4;
    port=5353;
    timeout=15;
    randomize_servers=on;
    proxy_only=on;
    purge_cache=off;
    #reject = 这里可以过滤国内地址，可选
    reject_policy=fail;
}
```

然后 ChinaDNS 把 `127.0.0.1:5050` 作为国外 DNS 即可。

**Comment by flipphos** [comment]
下述是我的配置pdnsd节选：
上游为自己的VPS 上的pdnsd非标端口。都用的的udp。


#OpenWRT端
#Update: 2015
#root@Gargoyle-x86:/etc/shadowsocks# cat /etc/pdnsd.conf
// Sample pdnsd configuration file. Must be customized to obtain a working pdnsd setup!
// Read the pdnsd.conf(5) manpage for an explanation of the options.
// Add or remove '#' in front of options you want to disable or enable, respectively.
// Remove '/*' and '*/' to enable complete sections.
 
global {
        perm_cache=2048;
        cache_dir="/var/pdnsd";
#       pid_file = /var/run/pdnsd.pid;
        run_as="nobody";
        server_port = xxxx;
        server_ip = 0.0.0.0;  # Use eth0 here if you want to allow other
                                # machines on your network to query pdnsd.
        status_ctl = on;
#       paranoid=on;       # This option reduces the chance of cache poisoning
                           # but may make pdnsd less efficient, unfortunately.
        query_method=udp_tcp;
        min_ttl=6h;       # Retain cached entries at least 15 minutes.
        max_ttl=48h;        # 1w = One week.
        timeout=10;        # Global timeout option (10 seconds).
        neg_domain_pol=on;
        udpbufsize=1024;   # Upper limit on the size of UDP messages.
}
 
# The following section is most appropriate if you have a fixed connection to
# the Internet and an ISP which provides good DNS servers.
server {
        label= “mydns";
          ip = V.P.S.1.ip;     #VPS1 IP
        ip = V.P.S.2.ip;  # VPS2 IP
        ip = V.P.S.3.ip;  # VPS3 IP
        port = xxxxx;
        proxy_only=on;     # Do not query any name servers beside your ISP's.
                           # This may be necessary if you are behind some
                           # kind of firewall and cannot receive replies
                           # from outside name servers.
        timeout=4;         # Server timeout; this may be much shorter
                           # that the global timeout option.
        uptest= none;         # Test if the network interface is active.
        interface=eth0;    # The name of the interface to check.
        interval=10m;      # Check every 10 minutes.
        purge_cache=off;   # Keep stale cache entries in case the ISP's
                           # DNS servers go offline.
        edns_query=on;    # Use EDNS for outgoing queries to allow UDP messages
                           # larger than 512 bytes. May cause trouble with some
                           # legacy systems.
#       exclude=.thepiratebay.org,  # If your ISP censors certain names, you may
#               .thepiratebay.se,   # want to exclude them here, and provide an
#               .piratebay.org,     # alternative server section below that will
#               .piratebay.se;      # successfully resolve the names.
}

**Comment by suikatomoki** [comment]
@bazingaterry 然后呢，这不符合问题要求啊？

**Comment by suikatomoki** [comment]
@bazingaterry 按照你的配置把 127.0.0.1:5050 作为国外 DNS 是可以解决国外udp丢包问题，但是怎么解决国内dns劫持？

**Comment by aa65535** [comment]
国内 DNS 不建议使用 TCP,
试试 https://github.com/aa65535/openwrt-dns-forwarder

**Comment by suikatomoki** [comment]
@aa65535  可以，谢谢了
