### ISSUE TITLE
ChinaDNS 不能使用国外 IP

### ISSUE THREAD

**Issue by atjason** [aa65535/openwrt-chinadns#55]
您好，
首先感谢您的 ChinaDNS!

问题是这样的，我目前在 OpenWRT 里使用 ShadowSocks + ChinaDNS，在解析 pbs.twimg.com (Twitter 的一个服务器）时：

- 如果我在上游服务器中设置的是：114.114.114.114,8.8.8.8，能够得到正确的 IP，比如 104.244.43.7
- 如果我在上游服务器中设置的是：211.140.188.188,8.8.8.8，则得到国内错误的 IP，比如 111.1.61.12；其中，211.140.188.188 是运营商的 DNS 服务器

再一步：

- 如果直接使用 dig @114.114.114.114 pbs.twimg.com，能得到正确的 IP
- 如果直接使用 dig @8.8.8.8 pbs.twimg.com，能得到正确的 IP
- 如果直接使用 dig @211.140.188.188 pbs.twimg.com，则得到国内错误的 IP

现在看起来，ChinaDNS 并没有应用这一原则：`国外 DNS 返回国外 IP 时，使用国外的 IP`。

请问，如何调试、或解决这一问题呢？为什么在这种情况下没有使用国外的 IP 呢？这是不是传说中的运营商 DNS 污染？最新的 ChinaDNS 貌似去掉了 -delay 之类的参数，还能怎么设置呢？谢谢。

**Comment by atjason** [comment]
更新：开启 ShadowSocks 的 UDP 转发，依然有问题。具体的：

- 在 ShadowSocks 将本地端口 5300 转发至 8.8.8.8:53
- 在 ChinaDNS 中将上游服务器设置为 211.140.188.188,127.0.0.1#5300

**Comment by atjason** [comment]
更新：目前改进的做法是：结合 dnsmasq
指定的国内域名，使用
	ISP 的 DNS
		优点：速度快，可得到 ISP 本身 114 等公开服务器更优的结果
		缺点：肯定被污染
	问题
		该列表太大，有 1.2MB，使用 sed 等工具匹配时，可能会很慢；另外，如果 ChinaDNS 中也使用相同的国内上游服务器，再使用该列表的意义不大，可以忽略些操作。
		
指定的国外域名，使用 	
	SS UDP 转发
		优点：最不可能被污染，也不会被国内域名服务器的错误结果所影响
		缺点：可靠性 = SS 服务器可靠性 * SS 服务器 UDP 转发可靠性，速度可能比 8.8.8.8 快、也可能慢
其他域名
	使用 ChinaDNS

**Comment by hdstar2009** [comment]
用chinadns+pdnsd
pdnsd通过tcp查询谷歌dns，pdnsd作为chinadns的国外查询server

**Comment by atjason** [comment]
@hdstar2009 那国内 DNS 用什么呢？114？

我主要是想用运营商的 DNS：211.140.188.188，这样可以返回对当前运营商比较友好的地址。而一旦用了 211.140.188.188，这会出现得到的 IP 并不被 ChinaDNS 扔掉的情况。感兴趣可以试试在你那把国内 DNS 改为 211.140.188.188，然后打开 twitter.com、刷新，看会不会有问题。

**Comment by hdstar2009** [comment]
我是用pdnsd+tcp查询作为国外dns
所以对于这些国外网站完全不成问题，
换了你的dns 也没问题
我的方案你可以看这个：https://github.com/aa65535/openwrt-chinadns/issues/56

**Comment by atjason** [comment]
@hdstar2009 好的，那我去研究下。

**Comment by aa65535** [comment]
试试搭配 https://github.com/aa65535/openwrt-dns-forwarder

**Comment by hdstar2009** [comment]
@aa65535 openwrt-dns-forwarder 用法怎样的？和chinadns相比有什么优劣势？

**Comment by aa65535** [comment]
@hdstar2009 与 chinadns 搭配使用，运行 dns-forwarder 之后，将其作为 chinadns 的上游使用.
比如  dns-forwarder 监听 `5300` 端口，上游 DNS 设置为 `8.8.8.8`, 然后 chinadns 上游服务器设置为 `114.114.114.114,127.0.0.1#5300` 即可

**Comment by benwwchen** [comment]
@aa65535 dns-forwarder 能返回正确的IP（向127.0.0.1:5300查询），但ChinaDNS仍然采用国内DNS（具体使用了10.8.8.8的内网DNS）的污染结果（向127.0.0.1:53533查询），ignore list是正常的，只是加了内网IP段10.8.0.0/16。

**Comment by aa65535** [comment]
@benwwchen dns-forwarder 的上游服务器 `127.0.0.1:5300` 是什么提供的？

问题应该是 10.8.8.8 结果返回比 127.0.0.1:5300 慢。

 可以手动执行 chinadns 并使用 -v 参数查看详情。

**Comment by hdstar2009** [comment]
chinadns到底是如何工作的？似乎没看到有个仔细的说明。
例如查询一个国内域名，如果进行的？查询一个国外域名又是如何处理的？

**Comment by aa65535** [comment]
@hdstar2009 参考 #59

**Comment by benwwchen** [comment]
@aa65535 抱歉没有说清楚。5300 是 dns-forwarder 的监听端口，上游没有修改，是 8.8.8.8。ChinaDNS 的监听端口为 53533。

从日志看似乎是 10.8.8.8 返回结果更快：
```
**/usr/bin/chinadns -p 53533 -s 10.8.8.8,127.0.0.1:5300 -c /etc/ignore.list -m -v**
Thu Sep  8 03:13:22 2016 request github.com from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:13:22 2016 response github.com from 10.8.8.8:53 - filter
Thu Sep  8 03:13:22 2016 response github.com from 127.0.0.1:5300 - pass
Thu Sep  8 03:13:42 2016 request www.google.com.hk from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:13:42 2016 response www.google.com.hk from 10.8.8.8:53 - pass
Thu Sep  8 03:13:42 2016 request www.google.com.hk from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:13:42 2016 response www.google.com.hk from 10.8.8.8:53 - 120.196.0.5, pass
Thu Sep  8 03:13:42 2016 request 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.4.4.e.a.2.5.e.2.2.0.0.0.0.0.2.0.ip6.arpa from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:13:42 2016 response 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.4.4.e.a.2.5.e.2.2.0.0.0.0.0.2.0.ip6.arpa from 10.8.8.8:53 - filter
Thu Sep  8 03:13:43 2016 response www.google.com.hk from 127.0.0.1:5300 - 216.58.194.195, pass
Thu Sep  8 03:13:43 2016 response 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.4.4.e.a.2.5.e.2.2.0.0.0.0.0.2.0.ip6.arpa from 127.0.0.1:5300 - pass
Thu Sep  8 03:13:43 2016 response www.google.com.hk from 127.0.0.1:5300 - pass
Thu Sep  8 03:13:43 2016 request 5.0.196.120.in-addr.arpa from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:13:43 2016 response 5.0.196.120.in-addr.arpa from 10.8.8.8:53 - filter
Thu Sep  8 03:13:43 2016 response 5.0.196.120.in-addr.arpa from 127.0.0.1:5300 - pass
```

而查 twitter.com 结果如下：
```
Thu Sep  8 03:15:34 2016 request twitter.com from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:15:34 2016 response twitter.com from 10.8.8.8:53 - pass
Thu Sep  8 03:15:34 2016 request twitter.com from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 03:15:34 2016 response twitter.com from 10.8.8.8:53 - 93.46.8.89, filter
Thu Sep  8 03:15:35 2016 response twitter.com from 127.0.0.1:5300 - pass
Thu Sep  8 03:15:35 2016 response twitter.com from 127.0.0.1:5300 - 199.59.148.10, 199.59.148.82, 199.59.150.7, 199.59.149.198, pass
```

请问有什么办法可以解决吗？

**Comment by aa65535** [comment]
建议配合 dig 看一下解析结果，类似
```
Thu Sep  8 03:15:34 2016 response twitter.com from 10.8.8.8:53 - pass
Thu Sep  8 03:15:35 2016 response twitter.com from 127.0.0.1:5300 - pass
```
这种没有打印出解析结果的，可能是 ipv6，或者结果为空，需要 dig 测试。

**Comment by benwwchen** [comment]
@aa65535 dig 结果如下：

twitter 正常解析：
```
#/usr/bin/chinadns -p 53533 -s 10.8.8.8,127.0.0.1:5300 -c /etc/ignore.list -m -v
Thu Sep  8 11:24:01 2016 request twitter.com from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 11:24:01 2016 response twitter.com from 10.8.8.8:53 - 37.61.54.158, filter
Thu Sep  8 11:24:01 2016 response twitter.com from 127.0.0.1:5300 - 199.59.150.7, 199.59.149.198, 199.59.148.10, 199.59.148.82, pass
```

google.com 和 google.com.hk 返回污染结果：
```
Thu Sep  8 11:25:02 2016 request www.google.com from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 11:25:02 2016 response www.google.com from 10.8.8.8:53 - 120.196.0.5, pass
Thu Sep  8 11:25:03 2016 response www.google.com from 127.0.0.1:5300 - 216.58.194.196, pass
```

而 google.co.jp 却能过滤掉 IPv4 的污染结果，但是 IPv6 的查询仍然是返回了污染的结果：
IPv4 only：
```
Thu Sep  8 11:38:43 2016 request www.google.co.jp from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 11:38:43 2016 response www.google.co.jp from 10.8.8.8:53 - 93.46.8.89, filter
Thu Sep  8 11:38:43 2016 response www.google.co.jp from 127.0.0.1:5300 - 216.58.192.3, pass
```
nslookup 结果（含IPv6）：
```
Thu Sep  8 11:43:08 2016 request www.google.co.jp from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 11:43:08 2016 response www.google.co.jp from 10.8.8.8:53 - pass
Thu Sep  8 11:43:08 2016 request www.google.co.jp from 10.8.8.8:53 127.0.0.1:5300
Thu Sep  8 11:43:08 2016 response www.google.co.jp from 10.8.8.8:53 - 93.46.8.89, filter
Thu Sep  8 11:43:09 2016 response www.google.co.jp from 127.0.0.1:5300 - pass
Thu Sep  8 11:43:09 2016 response www.google.co.jp from 127.0.0.1:5300 - 216.58.192.3, pass
```

所以是由于国内 DNS 返回的结果是国内 IP，所以 ChinaDNS 就直接采用了？需要在 ignore.list 中加入该 IP 来解决？
