### ISSUE TITLE
chinadns并没有生效？

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-chinadns#56]
一直都是用chinadns+pdnsd 
chinadns设置国内用114.114.114.114 国外就是用127.0.0.1：1053（这个是路由上的pdnsd程序）
平时上网什么也没发现什么特别问题，youtube这些网站都很正常打开。
昨天开始看pdnsd的说明手册，用pdnsd-ctl dump检查pdnsd的缓存，发现qq.com taobao.com youku.com各种国内域名都在pdnsd的缓存里面。而根据chinadns的设计，这些国内的域名不是因为被chinadns的国内dns接管来解析，而不应该出现在pdnsd缓存中吗（出现在pdnsd不是说解析域名的时候是提交给负责国外域名的127.0.0.1:1053了？）
不知道我这样理解是否正确。
现在想想平时手机上qq浏览器的一些图片显示是有点慢，会不会就是被pdnsd的国外dns解析的原因？

**Comment by aa65535** [comment]
chinadns 无法区分一个域名是不是国内域名，只是在查询到结果之后通过 chnroute 分辨 IP 是否属于国内.
在查询时, chinadns 会向所有设置的上游服务器发送查询请求, 所以 pdnsd 自然会收到国内域名查询.
如果使用 chinadns + pdnsd , 则不应该开启 pdnsd 的缓存, 否则 pdnsd 的响应要比设置的国内 DNS 服务器要快，自然取得的是 pdnsd 中缓存的结果, DNS 缓存应该放到 chinadns 下游.

**Comment by hdstar2009** [comment]
chinadns如果从pdnsd缓存获得结果，不是还要根据chnroute来分别ip是否国内吗？如果qq.com这些域名获得的是国外ip结果，chinadns下一步如何处理？会去查询上游的国内dns server吗？
dns缓存放到chinadns的下游，这个没想到怎么做？提示下？

**Comment by aa65535** [comment]
在不开启双向过滤的情况下，对于国内 IP, 只接受最先得到的结果

**Comment by hdstar2009** [comment]
我在你这个项目和原始chinadns项目看了，似乎都没有找到chinadns一些相关参数的说明，例如你上面说的双向过滤，是指什么，我似乎就没看到说明
还有看到有人提到的指针压缩，是什么作用，也没见到说明。是我找的方法不对？

**Comment by hdstar2009** [comment]
补充一下：dig @127.0.0.1 -p 5353 qq.com 
这样让chinadns查询qq.com域名吧
返回的结果是国内的。测试了taobao.com，也是返回国内两个ip
这难道说我用119.29.29.29,127.0.0.1:1053(pdnsd本地)是能正确获得国内网站的解析？、
越来越混乱了。
