### ISSUE TITLE
无法正确应对 Dnscrypt-proxy 的 OPT 回应

### ISSUE THREAD

**Issue by t123yh** [aa65535/openwrt-chinadns#57]
如图，我的电脑 IP 为 192.168.1.100，路由器 IP 为 192.168.1.1。
当我在路由器 192.168.1.1 上运行 dnscrypt，端口为 53，并将电脑 DNS 设为 192.168.1.1，可以正常解析 twitter 地址（如图）：

![7](https://cloud.githubusercontent.com/assets/8972552/16894189/ff87a8b6-4b81-11e6-8010-dfb232b04583.png)
![8](https://cloud.githubusercontent.com/assets/8972552/16894188/f75813a6-4b81-11e6-864b-59b9d0ad6ce7.png)

当我在路由器 192.168.1.1 上运行 chinadns，端口为 53，服务器 IP 为 119.29.29.29,192.168.1.100，并且在电脑上以同样参数运行 dnscrypt（便于抓包分析），再查询 twitter 地址，即无法查询（如图）：

![10](https://cloud.githubusercontent.com/assets/8972552/16894219/890abe16-4b82-11e6-9483-fa3e821ecae1.png)

![9](https://cloud.githubusercontent.com/assets/8972552/16894221/8c5518fa-4b82-11e6-878e-141f83810c0e.png)
（注意，chinadns 并未给出来自电脑的 twitter.com 解析结果的 IP 地址，抓包结果也显示电脑没有给出 IP 地址）

![12](https://cloud.githubusercontent.com/assets/8972552/16894233/e60cd73e-4b82-11e6-8e34-e43aa1098e30.png)

如果需要抓包文件，我可以上传。

**Comment by lixingcong** [comment]
为什么不直接在路由器上使用dnscrypt-proxy？

[dnscrypt for openwrt](https://github.com/lixingcong/dnscrypt-proxy-openwrt)

**Comment by t123yh** [comment]
@lixingcong 
在电脑上是便于抓包。在路由器上结果是一样的。

**Comment by t123yh** [comment]
问题解决了：是我作死，对dnscrypt开了-T，所以只能走TCP，而ChianDNS又不兹瓷，就GG了
