### ISSUE TITLE
No longer support specifying trailing space and comma seperated DNS servers.

### ISSUE THREAD

**Issue by legendtang** [aa65535/openwrt-chinadns#61]
```
chinadns -m -p 5353 -c /etc/chinadns_chnroute.txt -s 114.114.114.114, 114.114.115.115, 127.0.0.1:5300
Segmentation fault
```

But `chinadns -m -p 5353 -c /etc/chinadns_chnroute.txt -s 114.114.114.114,114.114.115.115,127.0.0.1:5300` is fine. It seems last changes break this.

**Comment by aa65535** [comment]
Always only allowed to use commas to separate the DNS servers.

BTW: Parameters with spaces should be wrapped in quotes.
