### ISSUE TITLE
本地dns被污染返回国内ip时，不会继续通过无污染dns解析

### ISSUE THREAD

**Issue by 523860169** [aa65535/openwrt-chinadns#65]
我配置的两个dns，第一个是isp的，第二个是中科大的，因为我是移动宽带，使用其他公共dns总是会有些常用网站无法访问，而用isp的dns就没这问题，所以我默认首选ISP的dns，但是ISP对google等会返回国内的ip地址，下面是我收集的，dig google时返回的，随机的，希望chinadns可以支持自定义污染IP
ignore-address=112.5.240.235
ignore-address=112.5.254.162
ignore-address=218.207.212.41
ignore-address=218.207.212.46
ignore-address=218.207.212.47
ignore-address=218.207.212.48
ignore-address=218.207.212.49
ignore-address=218.207.212.52
ignore-address=222.47.21.14
ignore-address=222.47.21.16
ignore-address=222.47.21.32
ignore-address=222.47.21.33
ignore-address=222.47.21.36
ignore-address=222.47.21.46

config chinadns
	option enable '1'
	option bidirectional '0'
	option chnroute '/etc/chinadns_chnroute.txt'
	option port '5353'
	option server '211.138.151.161,202.141.176.93#5353'

**Comment by aa65535** [comment]
chinadns 是支持使用 blacklist 的，可以在 [init script](https://github.com/aa65535/openwrt-chinadns/blob/master/files/chinadns.init#L49) 后面加上  `-l /path/to/file`
文件内容类似：
```
112.5.240.235
112.5.254.162
218.207.212.41
218.207.212.46
218.207.212.47
218.207.212.48
218.207.212.49
218.207.212.52
222.47.21.14
222.47.21.16
222.47.21.32
222.47.21.33
222.47.21.36
222.47.21.46
```

**Comment by 523860169** [comment]
@aa65535 我在/etc/init.d/chinadns的第49行修改成这样
`		$parms -m -l /etc/chinsdns_blacklist.txt
`
然后新建/etc/chinsdns_blacklist.txt，粘贴那些污染ip，重启chinadns，结果dig还是获取到了112.5.240.235这个污染ip

**Comment by aa65535** [comment]
@523860169 需要去掉`-m` 。

**Comment by 523860169** [comment]
@aa65535 去掉了-m 还是返回112.5.240.235这个污染ip
