### ISSUE TITLE
ChinaDNS 参数疑问

### ISSUE THREAD

**Issue by pexcn** [aa65535/openwrt-chinadns#66]
请问上游 DNS 填写 `223.5.5.5,127.0.0.1:5300` 和 `223.5.5.5,127.0.0.1#5300` 的区别是什么？
(把 `:` 换成 `#`)

**Comment by aa65535** [comment]
https://github.com/aa65535/openwrt-chinadns/releases/tag/v1.3.2-2

**Comment by pexcn** [comment]
谢谢
