### ISSUE TITLE
解析 Google 域名的问题

### ISSUE THREAD

**Issue by pexcn** [aa65535/openwrt-chinadns#68]
有时候会解析到 Google 在北京的服务器里去了，图：
![gg](https://cloud.githubusercontent.com/assets/4590439/21743200/685a0650-d538-11e6-8b0c-9a914000ccbd.png)

**Comment by pexcn** [comment]
补图
![11](https://cloud.githubusercontent.com/assets/4590439/21743209/b5068500-d538-11e6-8448-50a3897d2905.png)
![ff](https://cloud.githubusercontent.com/assets/4590439/21743211/b6625488-d538-11e6-9782-7ed59c32697d.png)

**Comment by pexcn** [comment]
似乎是 Chrome 的问题？用 IE 却正常。

**Comment by pexcn** [comment]
另外，用 `dig` 命令查询到的 DNS 也正常，`ipconfig /flush` 重启 Chrome 也一样 404 页面。然后我重启了电脑，再打开 Chrome，居然正常了。。

**Comment by cokebar** [comment]
use dnsmasq rules, force these domain resolve from foreign dns.

**Comment by pexcn** [comment]
但是这是哪里的问题呢？不像是 ChinaDNS 的问题。

**Comment by cokebar** [comment]
@pexcn 此应为ChinaDNS误判，是fake ip。在现在污染IP完全随机的情况下会有各种bug。
注意：使用ChinaDNS做防污染并不是他主要的作用，并且在当前的环境下，尽量不要单纯使用CHinaDNS作为防污染手段，一来有bug，二来DNS服务器是根据你的实际IP返回的解析结果而不是根据代理服务器的IP，这样造成解析出的IP可能离你的实际位置近但是离代理较远，反而速度慢。比如说服务器在美国，但是单纯使用chinadns就可能造成解析google.com到香港的情况。
ChinaDNS的主要作用是优选解析结果，国外DNS一定要通过代理走；这样既杜绝了污染也可以获取最佳的解析结果。

**Comment by pexcn** [comment]
但是 dig 出来的结果是正确的，只是 Chrome 访问的地址错误 @cokebar

**Comment by aa65535** [comment]
解析结果是否正确，应当使用 `dig` 命令去检查而不是 Chrome, 你的情况更像是 Chrome 使用了另外的代理，或者远程DNS解析。
