### ISSUE TITLE
增加自动修改dnsmasq设置的功能

### ISSUE THREAD

**Issue by cokebar** [aa65535/openwrt-chinadns#69]
我目前使用的固件中的版本是以你的这个版本为基础修改过来的，有个自动修改dnsmasq配置的功能感觉不错，自动添加chinadns到dnsmasq设置中，并取消resolvefile。
节选启动脚本：
start_chinadns() {
	[ "$enabled" = 1 ] || return 0
	[ "$automod" = 1 ] && {
		uci del dhcp.@dnsmasq[-1].server
		uci del dhcp.@dnsmasq[-1].resolvfile
		uci set dhcp.@dnsmasq[-1].noresolv=1
		uci add_list dhcp.@dnsmasq[-1].server=127.0.0.1#$port
		uci commit dhcp
	}
	append_parm $1 port "-p"
	append_parm $1 server "-s"
	append_parm $1 chnroute "-c"
	append_bool $1 bidirectional "-d"
	service_start /usr/bin/chinadns \
		$parms -m
	return $?
}

stop() {
	[ "$enabled" = '0' ] && {
		[ "$automod" = '1' ] && {
			uci del dhcp.@dnsmasq[-1].server
			uci del dhcp.@dnsmasq[-1].noresolv
			uci set dhcp.@dnsmasq[-1].resolvfile=/tmp/resolv.conf.auto
			uci commit dhcp
		}	
	service_stop /usr/bin/chinadns
	/etc/init.d/dnsmasq restart
	}
}

**Comment by aa65535** [comment]
参考 https://github.com/shadowsocks/luci-app-shadowsocks/issues/78
