### ISSUE TITLE
请问新版本中的双向过滤的意思是？

### ISSUE THREAD

**Issue by cokebar** [aa65535/openwrt-chinadns#7]
新版本更新了什么样的防污染策略还不是很清楚，求解释一下双向过滤，感谢！

**Comment by aa65535** [comment]
https://github.com/clowwindy/ChinaDNS-C#advanced
这个其实是 1.1.8 添加的功能，
当国外DNS服务器返回的查询结果是国内IP，则过滤掉这个结果，
是否属于国内，是根据 chnroute 判断。

**Comment by xcjiang** [comment]
双向过滤的目的是？有何必要？
