### ISSUE TITLE
建议使用少量路由，覆盖大量 IP 段方案

### ISSUE THREAD

**Issue by liudongmiao** [aa65535/openwrt-chinadns#71]
具体，请参见：https://github.com/liudongmiao/chinaip

> 一般来说，使用不到800条路由可以覆盖中国97%的IP，比直接使用4000+条原生少了很多。 即使是要完全覆盖，也可以节省大约1000条路由。考虑到中国的服务提供商大多使用大范围的IP段，小范围的分给宽带用户，经过实测，使用16。

而另外的 3%，绝大部分还是家庭所用的宽带等，并不对外提供服务。

**Comment by daiaji** [comment]
@aa65535 
https://github.com/ashi009/bestroutetb/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
还有这么个方案

**Comment by aa65535** [comment]
这样会导致 ChinaDNS 工作不正常，所以不会采用，如果你们需要的话自己分开设置即可。
