### ISSUE TITLE
ChinaDNS - 未运行

### ISSUE THREAD

**Issue by millionart** [aa65535/openwrt-chinadns#74]
昨晚莫名其妙上不去网，以为是ss挂了，结果排查了一晚上发现chinadns无法启用了，什么也没做，重装也不行，没法确认原因……
版本1.3.2-4

**Comment by aa65535** [comment]
执行 `/etc/init.d/chinadns start` 查看是否有报错。

**Comment by millionart** [comment]
毫无反应

**Comment by millionart** [comment]
还有其他方法查看信息么……

**Comment by millionart** [comment]
卸载后清除配置文件和路由表再全新安装业无法运行……

**Comment by siwind** [comment]
有可能是端口5353被占用（当启用IPv6时），试一试将Chinadns的端口改为： 5330

**Comment by LiLejia** [comment]
@siwind  Right.

**Comment by tufu9441** [comment]
我也遇到了这个问题，我用的是pandorabox固件，自己上传最新版的ChinaDNS 1.3.3-1和luci-app-chinadns 1.6.2的ipk然后手动opkg安装，ChinaDNS怎么都启动不了，显示未运行。但从固件自带的源里安装ChinaDNS 1.3.2-3和luci-app-chinadns后就可以正常运行，很奇怪。我之所以想安最新版的ChinaDNS是因为我怀疑1.3.2的版本会经常出现断流的现象。

**Comment by gili-gili** [comment]
> 有可能是端口5353被占用（当启用IPv6时），试一试将Chinadns的端口改为： 5330

正解，非常感谢完美解决
