### ISSUE TITLE
这种情况下无法工作吗？

### ISSUE THREAD

**Issue by suikatomoki** [aa65535/openwrt-chinadns#75]
为了解决运营商dns劫持问题
我使用了httpdns监听在5533端口
https://github.com/KCCat/dnspod-httpdns-proxy/blob/master/httpdns.py

单独使用httpdns是可以正常解析的 作为Dnsmasq上游的话

![qq 20170728175826](https://user-images.githubusercontent.com/10336224/28712715-c3315f0e-73be-11e7-9f39-da11e2df95b5.png)

问一下有没有啥简单粗暴的方法同时解决污染和劫持问题 
@aa65535

**Comment by suikatomoki** [comment]
并不是chinadns的问题 
换了个httpdns程序就好了
https://github.com/chenhw2/dnspod-http-dns

@KCCat 能修复一下吗

**Comment by aa65535** [comment]
这种配置, chinadns 只认为你设置了两个国外 dns, 而没有国内 dns.

**Comment by suikatomoki** [comment]
@aa65535 额  不管如何  @KCCat 程序肯定有点问题 直接罢工了 
那么能解决这个问题吗  修改一下逻辑 以便解决运营商劫持问题

**Comment by KCCat** [comment]
如果没有脚本抛出错误的日志的话我也没有办法测试是什么地方有问题.  
dnspod-httpdns本来没有提供完整的dns功能,我的实现也没有按照DNS规范来的  

我不太了解chinadns工作原理,不过你想防止国内污染,又想国外解析正确的话  
用```ip-prefix/httpdns.py```分支的版本就好了  
在脚本里面写好中国的IP段,不在这个段内或其他不支持的请求都不会返回结果  
然后你在dnsmasq上设置```all-servers```然后在dnsmasq填上所有上游DNS,dnsmasq就会向所有上游并发请求,先哪个上游先回应结果,就用哪个结果.  
只要解析国外域名的上游比我的脚本响应慢就行了.
