### ISSUE TITLE
Error infor of "local_ns_initparse: Message too large" in System Log with 1.3.2-5

### ISSUE THREAD

**Issue by snapper2tt** [aa65535/openwrt-chinadns#78]
My Linksys WRT1900AC v2 is running official LEDE 17.01.2, I used to run ChinaDNS 1.3.2-4 and everything was fine, but after upgrading to 1.3.2-5 recently, the error information below keeps showing in my system log at a 4-sec interval. Any suggestion on how to get rid of it? Thanks!

Sat Sep  2 22:13:03 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:03 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:07 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:07 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:11 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:11 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:15 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:15 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:19 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:19 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:23 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:23 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:27 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:27 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:31 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:31 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:35 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:35 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:39 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:39 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:43 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:43 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:47 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:47 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:51 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:51 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:55 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:55 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:13:59 2017 daemon.err chinadns[8308]: Sat Sep  2 22:13:59 2017 chinadns.c:628 local_ns_initparse: Message too large
Sat Sep  2 22:14:03 2017 daemon.err chinadns[8308]: Sat Sep  2 22:14:03 2017 chinadns.c:628 local_ns_initparse: Message too large

**Comment by reusu** [comment]
same

**Comment by reusu** [comment]
/usr/bin/dns-forwarder -b 127.0.0.1 -p 5533 -s 208.67.222.222#5353
/usr/bin/chinadns -m -p 5353 -s 114.114.114.114,127.0.0.1#5533 -c /etc/china.rule

**Comment by shikkoku** [comment]
我把国内的DNS那部分替换成ISP的DNS就没再报错了,之前尝试设置成百度的DNS（支持DNSSEC）,dns-forwarder的国外dns我试过其他的，最后发现诸多问题还是用回了8.8.8.8。

**Comment by aa65535** [comment]
fix via https://github.com/aa65535/openwrt-chinadns/commit/6d24a5294ab4bdaf798eea8bf635ae47a23b1c0b

**Comment by xueyichen** [comment]
still have this pro,when install 1.3.2-6

Thu Oct 26 21:41:05 2017 chinadns.c:628 local_ns_initparse: Message too long
Thu Oct 26 21:41:09 2017 chinadns.c:628 local_ns_initparse: Message too long
Thu Oct 26 21:41:13 2017 chinadns.c:628 local_ns_initparse: Message too long
Thu Oct 26 21:41:17 2017 chinadns.c:628 local_ns_initparse: Message too long
Thu Oct 26 21:41:21 2017 chinadns.c:628 local_ns_initparse: Message too long

**Comment by tacuar** [comment]
still have the same problem after installing 1.3.2-6, problem not solved yet.

**Comment by rule2c** [comment]
still have thie issue.

**Comment by s7lx** [comment]
still have the same problem

**Comment by tacuar** [comment]
@s7lx  use 1.3.2-4 and i do not have this issue with this version

**Comment by cherrot** [comment]
same issue here with 1.3.2-8

```
Wed Nov  7 00:04:38 2018 daemon.err chinadns[8588]: Wed Nov  7 00:04:38 2018 chinadns.c:708 local_ns_initparse: Message too large
```
