### ISSUE TITLE
Renaming Upstream into ChinaDNS

### ISSUE THREAD

**Issue by clowwindy** [aa65535/openwrt-chinadns#8]
The project will be renamed from ChinaDNS-C into ChinaDNS (Python version will be renamed into ChinaDNS-Python). I'm not sure if this will make big trouble(i.e. package name change, git repo url change, configuration key change, etc). If it is, I think we'd better just change the url, rather than the package name.

**Comment by aa65535** [comment]
如果 ChinaDNS Python 只是作为 ChinaDNS-C 在 Windows 上的补充，我觉得可以改名。
但是修改项目名称的话， ChinaDNS Python 原来的链接就不会正确地重定向了。

**Comment by clowwindy** [comment]
ChinaDNS Python 用的人不多，Windows 上还是用 PAC 比较适合。

**Comment by clowwindy** [comment]
已经改过来了。
