### ISSUE TITLE
keeps on showing up "chinadns.c message too large"

### ISSUE THREAD

**Issue by tacuar** [aa65535/openwrt-chinadns#82]
Estimated AA65535,

I'm running LEDE Reboot 17.01.3 r3533-d0bf257c46 / LuCI lede-17.01 branch (git-17.232.21093-079f65a)
Kernel Version | 4.4.89

I run ChinaDNS 1.3.2-5 version and set Upstream Servers 114.114.114.114,127.0.0.1:5300 to dns-forwarder.

In system log it keeps showing up "chinadns.c message too large" .

Someone suggest to modify the the buf_size to 1024, is that correct?

This can be done in the OP firmware somewhere or, this could be modified somewhere in the sourcecode before compiling the ipk for chinadns?

Thank you for your time!

**Comment by tacuar** [comment]
Mon Oct 16 10:08:48 2017 daemon.err chinadns[813]: Mon Oct 16 10:08:48 2017 chinadns.c:628 local_ns_initparse: Message too large
Mon Oct 16 10:08:48 2017 daemon.err chinadns[813]: Mon Oct 16 10:08:48 2017 chinadns.c:628 local_ns_initparse: Message too large
Mon Oct 16 10:08:53 2017 daemon.err chinadns[813]: Mon Oct 16 10:08:53 2017 chinadns.c:628 local_ns_initparse: Message too large
Mon Oct 16 10:08:53 2017 daemon.err chinadns[813]: Mon Oct 16 10:08:53 2017 chinadns.c:628 local_ns_initparse: Message too large
Mon Oct 16 10:08:58 2017 daemon.err chinadns[813]: Mon Oct 16 10:08:58 2017 chinadns.c:628 local_ns_initparse: Message too large
Mon Oct 16 10:08:58 2017 daemon.err chinadns[813]: Mon Oct 16 10:08:58 2017 chinadns.c:628 local_ns_initparse: Message too large

**Comment by aa65535** [comment]
fix via https://github.com/aa65535/openwrt-chinadns/commit/6d24a5294ab4bdaf798eea8bf635ae47a23b1c0b

**Comment by tacuar** [comment]
Very kind of you aa65535.

Thank you for your contribution !!!
