### ISSUE TITLE
chinadns.c message too long problem might be due to wrong use of pdnsd

### ISSUE THREAD

**Issue by tacuar** [aa65535/openwrt-chinadns#85]
previously i got this error notice in syslog constantly .

then i update to the latest chinadns and still got the same problem, so i re-compile the lede firmware without pre-compiling pdnsd or dnscrypt-proxy things into the firmware.

after burning the router with the pure firmware and with old chinadns installed onto it, problem and error notice stop appearing.

**Comment by tacuar** [comment]
so i suppose this is not about the problem of chinadns itself

**Comment by mmd1989** [comment]
my route does not install  pdnsd or dnscrypt-proxy, but Same syslog like `local_ns_initparse: Message too large ` occurring when my MITV is used, its weird

**Comment by muronghan** [comment]
最近"local_ns_initparse: Message too large" 在system log里不断重现。自己编译的LEDE Reboot 17.01-SNAPSHOT r3858，，，（核4.4.120）

**Comment by Biercenter** [comment]
@muronghan 我最近用lede17.01.4官方imagebuild版，安装集成了chinadns+dns-forwarder+shadowsocks-libev，家里也有小米电视，最近logread里全是chinadns.c:628 local_ns_initparse: Message too large的信息。可是几个月前同样的参数编译的固件又没有这个信息，有点怪！

**Comment by mmd1989** [comment]
@Biercenter 小米电视开机就有这条报错，4秒一次非常准时
That's error occurs every 4 s when MITV working, on schedule

**Comment by Biercenter** [comment]
@mmd1989 确实是的，我关掉小米电视就没有，开着一直跳出这条消息

**Comment by hdstar2009** [comment]
我也在路由日子里面看到大量的这样的信息:
Fri May 18 15:42:47 2018 daemon.err chinadns[1717]: Fri May 18 15:42:47 2018 chinadns.c:628 local_ns_initparse: Message too long
并没有楼上说的小米电视,有sony电视装了kodi,难道和这个有关系?

**Comment by mmd1989** [comment]
@hdstar2009 看上面的情况估计是投屏软件引起的，看看是不是电视上也有乐播投屏这类app
@aa65535 dns转发里设置127.0.0.1没有改善，除了日志里有错误信息、访问控制里的设置对tv不起作用外，倒是使用上没有什么影响

**Comment by aa65535** [comment]
试试 v1.3.2-8

**Comment by mmd1989** [comment]
chinadns升级到1.3.2-8；luci升级到1.6.2-1并设置监听127.0.0.1后问题解决，感谢
