### ISSUE TITLE
Is possible for a deployment of GFWLIST on ChinaDNS?

### ISSUE THREAD

**Issue by tacuar** [aa65535/openwrt-chinadns#88]
ChinaDNS has a list at this moment:   chinadns_chnroute.txt  under /etc

Is possible to develop a GFWLIST function on ChinaDNS luci ?

At this moment the ChinaDNS divides ChinaDNS and the rest foreign DNS list, is very good and easy.

Is possible to use GFWLIST feature on luci-app-chinadns?  by domains.

Options would be ,

1. only forward GFWLIST
2. only forward User defined domains
3. forward GFWLIST and user defined domains
4. Global Proxy

**Comment by aa65535** [comment]
No plan for this.
