### ISSUE TITLE
请问现在双向过滤是默认开启了吗？

### ISSUE THREAD

**Issue by pexcn** [aa65535/openwrt-chinadns#89]
根据这行 https://github.com/shadowsocks/ChinaDNS/blob/master/src/chinadns.c#L903

```
  -d                    off enable bi-directional CHNRoute filter\n\
```

意思是加上 `-d` 参数来关闭双向过滤吗？（英文不太好，见笑了~）

如果是，https://github.com/aa65535/openwrt-dist-luci 这个项目的 chinadns 模块也要更新一下了，它勾选了 `启用双向过滤` 会把 `-d` 参数加上的。

**Comment by aa65535** [comment]
默认关闭，加 `-d` 是开启。

**Comment by pexcn** [comment]
https://github.com/shadowsocks/ChinaDNS/blob/master/src/chinadns.c#L797 真的是，谢谢
