### ISSUE TITLE
ChinaDNS在路由器的/etc/config/没有chinadns文件，导致luci-app-chinadns无法启用

### ISSUE THREAD

**Issue by mrken2004** [aa65535/openwrt-chinadns#9]
你好！
很感谢您开发并维护的chinadns for openwrt版。在luci-app-chinadns发布后，在编译openwrt固件的时候始终在luci界面找不到。shadowsocks的可以。今天偶尔看了一下openwrt-dist-luci目录里的文件，发现chinadns.lua文件中有判断语句：
function index()
	if not nixio.fs.access("/etc/config/chinadns") then
		return
	end
而在openwrt的SDK中选择chiandns和luci-app-chinadns后编译完成的固件中，/etc/config目录里并没有chinadns文件，shadowssocks文件是有的。刚才手动创建了一个，现在在luci的配置界面可以看到chinadns了。
可否改进一下？谢谢！

**Comment by aa65535** [comment]
/etc/config/chinadns 是在 ChinaDNS 中(即本项目)，不是在 luci-app-chinadns 中。
https://github.com/aa65535/openwrt-chinadns/blob/172be22/Makefile#L53-L54

luci-app-chinadns 需要搭配本项目提供的 Makefile 编译的软件包。
