### ISSUE TITLE
二进制托管站挂掉了

### ISSUE THREAD

**Issue by s7lx** [aa65535/openwrt-chinadns#91]
http://openwrt-dist.sourceforge.net/archives/ChinaDNS/1.3.2-6/ 无法打开

**Comment by Biercenter** [comment]
http://openwrt-dist.sourceforge.net 过年之前就看到数据迁移，好了几天，期间又维护。昨天打包固件发现又无法下载了，看到数据迁移，到今天还是打不开。

**Comment by pexcn** [comment]
分享一个
ar71xx: https://github.com/openwrt-dev/feeds/tree/ar71xx
ramips: https://github.com/openwrt-dev/feeds/tree/ramips
