### ISSUE TITLE
想问下网件的3700v4应该装哪个版本啊？试了试了ar71xx和ramips_24kec都不行

### ISSUE THREAD

**Issue by xianshanlai** [aa65535/openwrt-chinadns#92]
路由已经装了openwrt的lede-17.01.4-ar71xx-nand-wndr3700v4-ubi-factory.img，装ChinaDNS时试了上面两个版本都提示：
Unknown package 'ChinaDNS'.
Collected errors:

    pkg_hash_fetch_best_installation_candidate: Packages for ChinaDNS found, but incompatible with the architectures configured
    opkg_install_cmd: Cannot install package ChinaDNS.
    下面命令返回：
    opkg print-architecture
    arch all 1
    arch noarch 1
    arch mips_24kc 10

**Comment by aa65535** [comment]
mips_24kc

**Comment by xianshanlai** [comment]
这个版本也报一样的错啊

BusyBox v1.25.1 () built-in shell (ash)

     _________
    /        /\      _    ___ ___  ___
   /  LE    /  \    | |  | __|   \| __|
  /    DE  /    \   | |__| _|| |) | _|
 /________/  LE  \  |____|___|___/|___|                      lede-project.org
 \        \   DE /
  \    LE  \    /  -----------------------------------------------------------
   \  DE    \  /    Reboot (17.01.4, r3560-79f57e422d)
    \________\/    -----------------------------------------------------------

root@LEDE:~# cd /tmp
root@LEDE:/tmp# opkg install ChinaDNS_1.3.2-6_ramips_24kec.ipk
Unknown package 'ChinaDNS'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for ChinaDNS found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package ChinaDNS.
root@LEDE:/tmp#

**Comment by aa65535** [comment]
http://openwrt-dist.sourceforge.net/packages/base/mips_24kc/ChinaDNS_1.3.2-6_mips_24kc.ipk

是 `mips_24kc` 不是 `ramips_24kec` ，不知道 ramips_24kec 是哪来的。

**Comment by xianshanlai** [comment]
好吧，我是从
https://github.com/aa65535/openwrt-chinadns/releases/tag/v1.3.2-6
这个页面的Precompiled Download里面找的，感觉名字像就下了。冏~
感觉我菜鸟的不行了，谢谢我再试试
