### ISSUE TITLE
当上游服务器挂掉一个后ChinaDNS就原地爆炸

### ISSUE THREAD

**Issue by HMoeGuo** [aa65535/openwrt-chinadns#95]
貌似在处理dns获取错误时候没做异常处理 比如上游服务器无法访问时候 导致服务直接堵塞 然后必须重启才能恢复

**Comment by nasbdh9** [comment]
比如重启PPPoE端口后很多时候要手动重启chinadns才可以正常工作...

**Comment by zyf0330** [comment]
使用两个上游服务器，第二个挂了的时候，就完全不能正常工作了

**Comment by ghluuuuuu** [comment]
直接自建bind，走根分流，不用这么麻烦了。
Close comment.
