### ISSUE TITLE
SS是如何搭配ChinaDNS使用的呢

### ISSUE THREAD

**Issue by helllkz** [aa65535/openwrt-chinadns#96]
最近在学习自己编译openwrt，之前使用梅林，国内是ISP的DNS，国外使用ChinaDNS，实现原理是什么呢？wiki里面写到了如何搭配dnsforwarder，那我想的应该是这样，不知道对不对：

1. 假设没有SS的情况，那就是dnsmasq->chinadns-dnsforwarder，返回正确的IP地址，之后使用这个IP地址通信，此时就算得到了google的正确IP地址，但是这个IP如果被GFW封了，依然是访问不了的
2. 如果这个时候加上了SS，那访问这个IP就会走SS
3. SS和DNS查询有关联吗？
4. SS的GFWList模式又和这个过程有什么关系呢？

**Comment by wangxin6** [comment]
1. 不对。没有SS的情况下，dnsforwarder不能查询国外的dns server，不能返回正确的IP地址。
2. 对
3. 有关。同1。
4. GFWList是配合dnsmasq工作的

**Comment by helllkz** [comment]
那这种情况的话，dnsforwarder的上游dns应该设置什么呢，直接用默认的8.8.8.8呢，还是需要配置成ss的端口转发的127.0.0.1:port呢

**Comment by wangxin6** [comment]
DNS-Forwarder:
Listen Port: 5311
Listen Address:127.0.0.1
DNS Server:8.8.8.8

ChinaDNS:
Listen Port:5353
Listen Address:0.0.0.0
CHNRoute File:/etc/chinadns_chnroute.txt
Upstream Servers: 114.114.114.114,127.0.0.1#5311
 
DHCP and DNS:
DNS forwardings:127.0.0.1#5353

**Comment by helllkz** [comment]
那这个和wiki里面写的是一样的，意思是ssr里面的端口转发其实没用，对吗？
